(* Extracted from RICH.nb. Definitions preserve original initialization-cell order. *)
(* Generated mechanically; validate in a clean Wolfram kernel before deleting legacy-original/. *)

(* ---- initialization cell 1 | 36aa5063-89c2-6c4e-896b-cb5397fd11fa ---- *)
Print["\<*==================================================================================================*\>"];

Print["\<*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*\>"];

Print["\<***--- rich ---***\>"];

Print["\<*VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV*\>"];

Print["\<*==================================================================================================*\>"];

(* ---- initialization cell 2 | cbbc84ba-e412-0349-889b-7eeef5430fe7 ---- *)
(*Get["\<C:\\Users\\Ale\\My Drive\\allRICHWMMA\\myNotebookInit.wl\>"]*)

(* ---- initialization cell 3 | f1641602-dd3d-fd49-a02a-b6fa9bbf8fb7 ---- *)


(* ---- initialization cell 4 | 633e5756-59cc-0244-95f5-25d4f1677bc6 ---- *)
checkNewCreatedSymbols[]

showContextInfo[]

(* ---- initialization cell 5 | 63aa4562-425b-7d4b-8bc5-563a6816fc23 ---- *)


(* ---- initialization cell 6 | 4d71be8f-a08b-8f40-be1f-e3e6c69beb8b ---- *)
(**)
(* HERE TO ALLOW CHANGE SPECIFIC OPTIONS BELOW *)
(**)
(*SetOptions[EvaluationNotebook[],StyleDefinitions->"\<myStyle.nb\>"];*)
(*SetOptions[EvaluationNotebook[],StyleDefinitions->"\<StandardReport.nb\>"]*)
(*SetOptions[EvaluationNotebook[],StyleDefinitions->"\<Default.nb\>"]*)
If[TrueQ[$Notebooks],
SetOptions[EvaluationNotebook[],StyleDefinitions->FileNameJoin[{NotebookDirectory[],"\<myStyle.nb\>"}]];
(**)
SetOptions[EvaluationNotebook[],AutoGeneratedPackage->Automatic];
SetOptions[EvaluationNotebook[],AutoMultiplicationSymbol->True];
SetOptions[EvaluationNotebook[],Background->LightGreen];
SetOptions[EvaluationNotebook[],CellEpilog:>SelectionMove[EvaluationNotebook[],Next,Cell]];
SetOptions[EvaluationNotebook[],CellProlog:>SelectionMove[EvaluationCell[],All,Cell]];
SetOptions[EvaluationNotebook[],InitializationCellEvaluation->False];
SetOptions[EvaluationNotebook[],InitializationCellWarning->False];
SetOptions[EvaluationNotebook[],Magnification->3/4];
SetOptions[EvaluationNotebook[],OutputSizeLimit->1000000];(*maximum size for explicit output*)
SetOptions[EvaluationNotebook[],PrivateNotebookOptions->{"\<FileOutlineCache\>"->False,"\<SafeFileOpen\>"->"\<IgnoreCache\>"}];
SetOptions[EvaluationNotebook[],ShowCellLabel->False];
SetOptions[EvaluationNotebook[],WindowMargins->{{0,Automatic},{Automatic,0}}];
SetOptions[EvaluationNotebook[],WindowSize->{Scaled[3/4],Scaled[1.0]}];(*SetOptions[EvaluationNotebook[],WindowSize->Full]*)
SetOptions[EvaluationNotebook[],WindowTitle->StringJoin["\< ------- \>",nbFileName]];
(**)
SetOptions[EvaluationNotebook[],"\<DynamicUpdating\>"->True];(* It looks ok, even if it does not affect the tick in the Evaluation Menu ??? *)
(**)]

(* ---- initialization cell 7 | d1c64479-7b6f-bb48-83e8-ab868308104a ---- *)
(*Once[*)
myNotebookInit`loadMyFile["\<CellStyleDataRules.wl\>"]
(*,"\<Notebook\>"];*)

(* ---- initialization cell 8 | a30e95e9-cf3c-434c-bf08-37c4ba510fea ---- *)
Print["\<*==================================================================================================*\>"];

Print["\<*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*\>"];

Print["\<***--- rich ---***\>"];

Print["\<*VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV*\>"];

Print["\<*==================================================================================================*\>"];

(* ---- initialization cell 9 | b56e9b72-7c75-4ae8-b7bf-101bd99f1bd9 ---- *)
(**)
(*SetOptions[$FrontEnd,"\<DynamicEvaluationTimeout\>"->30];*)
(*SetOptions[$FrontEnd,"\<DynamicUpdating\>"->True];*)

(* ---- initialization cell 10 | cdf0c954-af07-4c83-a714-fa8939a1d8bc ---- *)
(**)
(*FrontEndExecute[FrontEndToken[EvaluationNotebook[],"\<SelectAll\>"]]*)
(*FrontEndTokenExecute["\<SelectionCloseAllGroups\>"]*)
(*FrontEndTokenExecute["\<SelectionOpenAllGroups\>"]*)

(* ---- initialization cell 11 | 911546c5-97ae-094c-b0fc-b12a16f3b093 ---- *)


(* ---- initialization cell 12 | 1f3b2078-f80d-f249-8bca-6e4d41e38df2 ---- *)
(**)
$HistoryLength=100;

(* ---- initialization cell 13 | ea20baf6-a03e-5c45-b32d-fac474fa8d8d ---- *)
(*
Print@Options[EvaluationNotebook[],AutoGeneratedPackage];
Print@Options[$FrontEnd,{"\<MessageOptions\>"}];
Print@Options[$FrontEnd,{"\<PrintAction\>"}];
Print@Options[EvaluationNotebook[],PrivateNotebookOptions];
Print@Options[EvaluationNotebook[],StyleDefinitions];
Print@Options[EvaluationNotebook[]];
*)

(* ---- initialization cell 14 | 70d291cd-8f40-d647-9128-ef5e7e3187a0 ---- *)
If[TrueQ[$Notebooks],With[{nb=EvaluationNotebook[]},If[MatchQ[nb,_NotebookObject],Print["\< INFO : Window Size : \>",CurrentValue[nb,WindowSize]];Print["\< NotebookInformation : \>",NotebookInformation[nb]];]]]

(* ---- initialization cell 15 | e7a89782-f2fc-9d47-b63f-32961bb901e6 ---- *)
(**)
(*deleteAllEmptyCellsInNotebook*)

(* ---- initialization cell 16 | d8b2fe91-3a26-af41-a929-3d1d5872fac9 ---- *)
(*Better as the first action to do, to avoid deleting errors in processing *)
(*NotebookDelete[Cells[EvaluationNotebook[],CellStyle->{"\<Output\>"}]];*)
(*NotebookDelete[Cells[EvaluationNotebook[],GeneratedCell->True]];*)
(**)

(* ---- initialization cell 17 | 8b4e2559-4147-384d-b267-c44d6e4de0c2 ---- *)
(* TAPULLO : still needed? 
https://mathematica.stackexchange.com/questions/250094/possible-bug-in-12-3-notebookdirectory-returns-not-the-notebooks-own-directo*)
(*CurrentValue[$FrontEnd,FrontEnd`FrontEndObjectFormat]="\<Legacy\>";*)

(* ---- initialization cell 18 | 1a8fe967-26b7-3240-aab1-831de3d59c89 ---- *)
(* list files in the directory for easier debugging of files loading*)
(*SetDirectory[NotebookDirectory[]]
filenames=Select[FileNames[],(StringTake[#,-2]==="\<nb\>")&];
Column[Map[Style[StringDrop[#,-3],"\<Times\>",12]&,filenames],Alignment->Left]*)

(* ---- initialization cell 19 | 0726014b-ee27-7445-b10f-5d6ef14fd01e ---- *)
checkNewCreatedSymbols[]

showContextInfo[]

Print["\< ************************************************************************************************* \>"];

Print["\< Start running  \>",myNotebookInit`timeStamp];

Print["\< Start running  \>",myNotebookInit`timeStamp];

Print["\< Start running  \>",myNotebookInit`timeStamp];

Print["\< t0=AbsoluteTime[]   \>",t0=AbsoluteTime[]];

Print["\< ************************************************************************************************* \>"];

(* ---- initialization cell 20 | ecf2a126-dc88-6c4c-a534-705387a0d373 ---- *)
(*SetOptions[EvaluationNotebook[],DockedCells->{Cell[BoxData[ToBoxes[ResourceFunction["\<NotebookOutlineMenu\>"][EvaluationNotebook[]]]]]}]*)

(* ---- initialization cell 21 | 72c181a9-4748-4147-81d4-e44a9a80f6ce ---- *)
(* output/print cells *)
If[Length@Cells[CellStyle->"\<Output\>"]>0,Cells[CellStyle->"\<Output\>"];Print[      "\<Length@Cells[CellStyle->Output]  \>",       Length@Cells[CellStyle->"\<Output\>"]      ]];


If[Length@Cells[CellStyle->"\<Print\>"]>0,Cells[CellStyle->"\<Print\>"];Print[     "\<Length@Cells[CellStyle->Print]  \>",           Length@Cells[CellStyle->"\<Print\>"]               ]];
(**)

(* ---- initialization cell 22 | f3939267-3a3b-d04c-b8e8-27ff78ffb70d ---- *)
(* Cells type inventory for this notebook *)
prettyPrintedCellStyleNumber

(* ---- initialization cell 23 | 1adde39e-0b68-4740-be8c-00cd5babc753 ---- *)


(* ---- initialization cell 24 | 9bdc5571-6876-b848-8dc2-368dfd44f720 ---- *)
(**************************************************************************************************)
(* my personal stuff *)
(**************************************************************************************************)
checkNewCreatedSymbols[]
showContextInfo[]
(*Once[*)
myNotebookInit`loadMyFile["\<base.wl\>"]
(*,"\<KernelSession\>"];*)
checkNewCreatedSymbols[]
showContextInfo[]

(* ---- initialization cell 25 | 5e866f18-0911-ad4f-a74d-69dcca533a32 ---- *)
(**************************************************************************************************)
(* my personal stuff *)
(**************************************************************************************************)
checkNewCreatedSymbols[]
showContextInfo[]
(*Once[*)
myNotebookInit`loadMyFile["\<statDataAnal.wl\>"]
(*,"\<KernelSession\>"];*)
checkNewCreatedSymbols[]
showContextInfo[]

(* ---- initialization cell 26 | 0bebdf56-af49-ef47-b13b-84d769f1b22e ---- *)


(* ---- initialization cell 27 | 987c3b35-1e0a-4a4c-8f34-778d69877eef ---- *)
BeginPackage["\<rich`\>",{"\<myNotebookInit`\>","\<base`\>","\<statDataAnal`\>"}]
(**)

Print["\< loading rich \>"]
(**)

Begin["\<`Private`\>"](* Begin Private Context *)

versionTAG="\<v.16-01-2025\>"

End[] (* End Private Context *)
(**)

checkNewCreatedSymbols[]

showContextInfo[]

(* ---- initialization cell 28 | 44515477-bc1e-4050-90e4-689d23168907 ---- *)
(**************************************************************************************************)
(* !@#$% VERY DANGEROUS!!! DO NOT USE *)
(*rplcNotExist[nex_,ex_]:=If[ValueQ[nex],Print["\< variable does exists \>"];Return[nex],Print["\< variable does exists \>"];Return[ex]];*)

(* ---- initialization cell 29 | cdcc3883-a443-db40-8f90-1ac4783a8585 ---- *)
(**)
(**************************************************************************************************)
Clear[debugPrintEnabledFlag];
Element[debugPrintEnabledFlag,Booleans];
debugPrintEnabledFlag=True;
Print["\< debugPrintEnabledFlag default is :    \>",debugPrintEnabledFlag];

(* ---- initialization cell 30 | 0c06cb37-a67b-1d40-ba7f-121da9e1aa3f ---- *)
(**)
(**************************************************************************************************)
ClearAll[debugPrint];
SetAttributes[debugPrint,HoldAll];
debugPrint[input__]:=Module[{},If[debugPrintEnabledFlag,(*Print["\< *** DEBUG \>"];*)Print[ input]]];
(**)
(**************************************************************************************************)
ClearAll[debugPrintD];
SetAttributes[debugPrintD,HoldAll];
(*debugPrintD[input__]:=Module[{},If[debugPrintEnabledFlag,Print[ToString[Hold@input],"\<    =      \>",input]]];*)
debugPrintD[input__]:=Module[{},If[debugPrintEnabledFlag,(*Print["\< *** DEBUG \>"];*)printD[input]]];
(**)
var=Sin[Pi/2];
printD[var];
debugPrintD[var];
printD[Sin[Pi/2]];
debugPrintD[Sin[Pi/2]];

(* ---- initialization cell 31 | f73f122f-40f0-4979-9964-e4fae6744d19 ---- *)
(**************************************************************************************************)
Clear[ticks,ticks2,grids];
ticks[min_,max_]:=Join[
Table[{i,Style[i,12],{.04,0}},{i,Ceiling[min],Floor[max]}],
Table[{j+.5,{.02,0}},{j,Round[min],Round[max-1],1}]];
ticks2[min_,max_]:=Table[If[EvenQ[i],{i,i,.06,Red},{i,i,.02,Blue}],{i,Ceiling[min],Floor[max],1}];
grids[min_,max_]:=Table[If[EvenQ[i],{i,Red},{i,Blue}],{i,Ceiling[min],Floor[max],1}];

(* ---- initialization cell 32 | c35b070b-b10a-4116-8f71-5c1117028596 ---- *)
(*(**************************************************************************************************)
Clear[cleanNum];
cleanNum[v_]:=Module[{y,s},
y=v/.s_String->0.0;
Return[y];
];
SetAttributes[cleanNum,Listable];
(**)*)

(* ---- initialization cell 33 | 12d4612a-f30c-43c3-9d8a-4821f87cd0e8 ---- *)
(**************************************************************************************************)
Clear[doMonitorAllVariables];
doMonitorAllVariables:=Module[{},
symbolsNew=Names["\<Global`*\>"];
If[Length@symbolsSave>0,
Print[TableForm[Sort[Complement[symbolsNew,symbolsSave]]]];
];
(*Remove/@Select[Names["\<Global`*\>"],StringMatchQ[#1,"\<y$\>"~~DigitCharacter..]&];*)
(*Reverse@Sort[{ByteCount[Symbol[#]],#}&/@Names["\<`*\>"]]*)
(*TableForm@Reverse@SortBy[Map[{#,ByteCount@ToExpression[#]}&,Names["\<Global`*\>"]],Last];*)
symbolsSave=Names["\<Global`*\>"];
];
(**)

(* ---- initialization cell 34 | 745a0248-df4d-4c08-a7d5-fdf6a82a61ff ---- *)
(**************************************************************************************************)
Clear[thePlotRange];
thePlotRange[h0_,v0_,hsiz_,vsiz_]:={{h0-hsiz/2,h0+hsiz/2},{v0-vsiz/2,v0+vsiz/2}};
(**)

(* ---- initialization cell 35 | 9a835481-ad3a-473d-8d5b-c559513cf574 ---- *)
(**************************************************************************************************)
Clear[myGridSkel];
myGridSkel[hMin_,hMax_,vMin_,vMax_,hStep_:100,vStep_:100]:={Table[k,{k,hMin,hMax,hStep}],Table[k,{k,vMin,vMax,vStep}]};
(*Print@TableForm@myGridSkel[-5000,+5000,-5000,+5000]*)
(**)

(* ---- initialization cell 36 | 2af5df15-01e0-4e06-89e3-dab46befb190 ---- *)
(**************************************************************************************************)
Clear[ExtractViewsFromGraphics];
ExtractViewsFromGraphics[ll_]:=Flatten[Union[Extract[ll,Position[ll,#]]&/@{ViewPoint->_,ViewCenter->_,ViewVertical->_,ViewAngle->_,ViewVector->_,ViewRange->_}]];
(**)

(* ---- initialization cell 37 | 335ff9a2-5d92-47a9-8ef8-e72fb0d7915a ---- *)
(**************************************************************************************************)

(* ---- initialization cell 38 | 05eaf0c2-5e2e-4d4a-b564-919118942567 ---- *)
Unprotect[thisGraphicsInset,thisGraphicsInsetText];

Clear[thisGraphicsInset,thisGraphicsInsetText];
(**)

thisGraphicsInsetText="\<N/A\>";

thisGraphicsInset:=Inset[Framed[Style[thisGraphicsInsetText,15],Background->LightYellow],Scaled[{1,1}],{0.99,0.99}];
(**)

SetOptions[{Plot,ListPlot,LogPlot,(*Graphics,*)Histogram},ImageSize->Large];

SetOptions[{Plot,ListPlot,LogPlot,(*Graphics,*)Histogram},Epilog->thisGraphicsInset];
(**)

Protect[(*thisGraphicsInset,thisGraphicsInsetText*)];
(**)

Options[#,Epilog]&/@{Plot,ListPlot,LogPlot,Graphics,Histogram}//Column

Print[Options/@{Plot,ListPlot,LogPlot,Graphics,Histogram}];
(**)

Print["\< tagDataPlot           = \>",tagDataPlot];

Print["\< thisDataPlotInset     = \>",thisDataPlotInset];

Print["\< thisGraphicsInsetText = \>",thisGraphicsInsetText];

Print["\< thisGraphicsInset     = \>",thisGraphicsInset];

Head@thisDataPlotInset

Head@thisGraphicsInset

OwnValues@thisDataPlotInset

OwnValues@thisGraphicsInset
(**)

Print@Plot[Sin[x],{x,0,99},AxesLabel->labelNmVsEv];

Print@ListPlot[{2,33,2,3,27},AxesLabel->labelNmVsEv];

(* ---- initialization cell 39 | 8f1898fd-b068-ef48-bbf7-876838554a79 ---- *)


(* ---- initialization cell 40 | cb011047-9d88-4fbe-88e5-3706a433928d ---- *)
(**************************************************************************************************)
showContextInfo[]
myNotebookInit`loadMyFile["\<physics-general.wl\>"];
showContextInfo[]
(**************************************************************************************************)

(* ---- initialization cell 41 | 67fdccc1-6e13-5341-97c8-d0def7f6da40 ---- *)


(* ---- initialization cell 42 | 17348d01-c6ee-1c46-89b6-69cbb9e6a6e5 ---- *)
(**************************************************************************************************)
(* \[Lambda]MinRef and \[Lambda]MaxRef can only be changed HERE *)
Unprotect[\[Lambda]MinRef,\[Lambda]MaxRef];
\[Lambda]MinRef=200;(*OK FOR LAPPDTM/MAPMT22*)
(*\[Lambda]MinRef:=270; FOR SIPMFBK/MPPCHPK // but are zero below 270-280 so you can use 200 anyway *)
\[Lambda]MaxRef=700;
Protect[\[Lambda]MinRef,\[Lambda]MaxRef];
(**)
Unprotect[nominalLengthRich1,nominalLengthRich2,nominalLengthALADDIN];
nominalLengthRich1=1000; (* used outside this routine *)(*should be around >1000: use 1000*)
nominalLengthRich2=2000; (* used outside this routine *)(*should be around >2000: use 2000*)
nominalLengthALADDIN=7500;(* used outside this routine *)
Protect[nominalLengthRich1,nominalLengthRich2,nominalLengthALADDIN];
(**)

(* ---- initialization cell 43 | 4d122955-d8bf-0f43-b5c5-f05287b9d75b ---- *)


(* ---- initialization cell 44 | 8f7dfeef-3cf6-e54e-a120-b6ba5e814cd4 ---- *)
(**************************************************************************************************)
showContextInfo[]
myNotebookInit`loadMyFile["\<inputDataForRICH.wl\>"];
showContextInfo[]
(**************************************************************************************************)

(* ---- initialization cell 45 | d3be098a-0020-1c4c-a00d-120819089ac4 ---- *)


(* ---- initialization cell 46 | 5fa1865c-8b3b-4e1d-8d02-da9c11c6d781 ---- *)
(*ClearAll[variableize];
variableize[text_String,prefix_:"\<id\>"]:=Module[{},
(*Symbol[StringJoin[prefix,StringReplace[Capitalize[ToLowerCase[text],"\<AllWords\>"],Whitespace->"\<\>"]]]*)
 Symbol[StringJoin[prefix,StringReplace[If[Length[prefix]==0,Decapitalize[text],Capitalize[text,"\<AllWords\>"]],Whitespace->"\<\>"]]]
];
SetAttributes[variableize,Listable]*)
(*head={"\<aaa\>","\< bbb \>","\<c\>","\< Ale\>","\<PPP\>"};*)
(*vars=variableize[head];*)
(*printD@head;*)
(*printD@vars;*)

(* full efficiency coefficients *)
effNames={
"\<effInGasRadAbsorption                       \>",
"\<effInMirror1IfNotWavLenDependentReflectivity\>",
"\<effInMirror2IfNotWavLenDependentReflectivity\>",
"\<effInQuartzPlateInterfaceReflectivity      \>",
"\<effInQuartzPlateAbsorption                 \>",
"\<effInLensesInterfaceReflectivity           \>",
"\<effInLensesAbsorption                      \>",
"\<effInSensorInterfaceReflectivity           \>",
"\<effInSensorGeomAcc                         \>",
"\<effInSensorCollectEff                      \>",
"\<effInSensorMultiplication                  \>",
"\<effInFrontEnd                              \>",
"\<effInDAQ                                   \>",
"\<effInReco                                  \>",
"\<effInAna                                   \>",
"\<effInAllTheOverallMarginFactor             \>"};
(*internal/partial efficiency coefficients*)
eff0Names={
"\<eff0GeoAccFactorInterColumns                \>",
"\<eff0GeoAccFactorInterEleCell               \>",
"\<eff0GeoAccFactorInterPixel                 \>",
"\<eff0InSensorGeomAccInBB                    \>",
"\<eff0InSensorGeomAccInBBRaw                 \>"};
(**)
(*--------------------------------------------------------------------------------*)
(* PATCH // TO BE IMPROVED *)
(*--------------------------------------------------------------------------------*)
allEff0:={
eff0GeoAccFactorInterColumns,
eff0GeoAccFactorInterEleCell,
eff0GeoAccFactorInterPixel,
eff0InSensorGeomAccInBB,
eff0InSensorGeomAccInBBRaw
};
allEff:={
effInGasRadAbsorption,
effInMirror1IfNotWavLenDependentReflectivity,
effInMirror2IfNotWavLenDependentReflectivity,
effInQuartzPlateInterfaceReflectivity,
effInQuartzPlateAbsorption,
effInLensesInterfaceReflectivity,
effInLensesAbsorption,
effInSensorInterfaceReflectivity,
effInSensorGeomAcc,
effInSensorCollectEff,
effInSensorMultiplication,
effInFrontEnd,
effInDAQ,
effInReco,
effInAna,
effInAllTheOverallMarginFactor
};
(*--------------------------------------------------------------------------------*)
(**)
eff0GeoAccFactorInterColumns=0.0;
eff0GeoAccFactorInterEleCell=0.0;
eff0GeoAccFactorInterPixel=0.0;
eff0InSensorGeomAccInBB=0.0;
eff0InSensorGeomAccInBBRaw=0.0;
(**)
effInLensesInterfaceReflectivity=0.0;
effInLensesAbsorption=0.0;
effInAllTheOverallMarginFactor=0.0;
effInDAQ=0.0;
effInFrontEnd=0.0;
effInGasRadAbsorption=0.0;
effInMirror1IfNotWavLenDependentReflectivity=0.0;
effInMirror2IfNotWavLenDependentReflectivity=0.0;
effInQuartzPlateAbsorption=0.0;
effInQuartzPlateInterfaceReflectivity=0.0;
effInReco=0.0;
effInAna=0.0;
effInSensorCollectEff=0.0;
effInSensorGeomAcc=0.0;
effInSensorInterfaceReflectivity=0.0;
effInSensorMultiplication=0.0;
(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\< Summary of all efficiencies used only internally \>"];
Print[TableForm@Transpose[{eff0Names,allEff0}]];
miniBanner["\< ---***--- Summary of all efficiencies ---***--- \>"];
Print[TableForm@Transpose[{effNames,allEff}]];
(**)
efficiencyDebugPrintout;

(* ---- initialization cell 47 | 51ec42a5-9408-e045-90b0-5bf3c3b1f3ae ---- *)
Clear[efficiencyDebugPrintout];

efficiencyDebugPrintout := Module[  {r1, r2}  ,
  miniBanner["\< Summary of all efficiencies used only internally - normally to ignore \>"];
  r1 = TableForm @ Transpose[{eff0Names, nf2/@allEff0}];
  Print[r1];
  miniBanner["\< ---***--- Summary of all efficiencies ---***--- \>"];
  r2 = TableForm @ Transpose[{effNames, nf2/@allEff}];
  Print[r2];
  Return[{r1, r2}]
];

(* ---- initialization cell 48 | ef293558-7a7d-4745-90c7-29bd595a383a ---- *)
Clear[plotCherenkovAngleChromaticLimits];

plotCherenkovAngleChromaticLimits[whichRICH_:0,rad_:"\<AIR\>"]:=Module[{localHisto,ttt,pMin,pMax,thetaCMax},
myNotebookInit`bigBanner["\< sensor not relevant here \>"];
printD[fileNameTagRichRad];
(*To define limits according to experiment // random so far*)
(*If [whichRICH==xyz && rad==abc,*)
pMin=10;
pMax=101;
thetaCMax=60;
(*];*)
miniBanner["\< p (GeV/c)   ---|---   chrAngle at \[Epsilon]Min   ---|---   chrAngle at \[Epsilon]Max \>"];
ttt=Table[{p,nf@tCAllPart[p,\[Epsilon]Min],nf@tCAllPart[p,\[Epsilon]Max]},{p,pMin,pMax,10}];
Print@ReplacePart[Insert[Grid[ttt],Alignment->Center,2],1->Prepend[First[Grid[ttt]],{"\<p (GeV/c)\>","\<chrAngle @ \[Epsilon]Min\>","\<chrAngle @ \[Epsilon]Max\>"}]];
localHisto=LogLinearPlot[{tCAllPart[p,\[Epsilon]Min],tCAllPart[p,\[Epsilon]Max]},{p,pMin,pMax},
PlotRange->{{pMin,pMax},{-1,thetaCMax}},
GridLines->Automatic,
ImageSize->Large,
AxesLabel->{"\<p (GeV/c)\>","\<\!\(\*SubscriptBox[\(\[Theta]\), \(c\)]\) (mrad)\>"},
PlotLabel->"\< emission - chromatic limits \>"];
Export["\<C:\\TEMP\\chrErrLimitsVersusMomentum-\>"<>fileNameTagRichRad<>"\<.pdf\>",localHisto,"\<PDF\>"]
];

(* ---- initialization cell 49 | f788b58c-187c-0941-9ae5-dea3d961c1a3 ---- *)
generatePhotonEnergy[num_,minEne_:\[Epsilon][\[Lambda]MaxRef],maxEne_:\[Epsilon][\[Lambda]MinRef]]:=Module[{w,photonEnergies,reNorma,solReNorma,p,q},
myNotebookInit`bigBanner["\< SIMULATION - bad to fix ..... \>"];
miniBanner["\< USING HERE THE DATA FROM LAST RUN OF calcDetectedPhotons \>"];
(*printD@whichRICH;printD@rad;printD@sensor;*)
Quiet[debugPrint["\< minEne = \>",minEne,"\< --- maxEne = \>",maxEne];
reNorma=1;
If[(normalizedInterpolatedIntegratedYieldEne[maxEne]!=1)||(normalizedInterpolatedIntegratedYieldEne[minEne]!=0)
,
Print["\< WARNING - renorma - normalizedInterpolatedIntegratedYieldEne[minEne] = \>",normalizedInterpolatedIntegratedYieldEne[minEne]];
Print["\< WARNING - renorma - normalizedInterpolatedIntegratedYieldEne[maxEne] = \>",normalizedInterpolatedIntegratedYieldEne[maxEne]];
solReNorma=First@Solve[
p*normalizedInterpolatedIntegratedYieldEne[maxEne]+q==precisionify[1.0]
&&
p*normalizedInterpolatedIntegratedYieldEne[minEne]+q==precisionify[0.0]
,{p,q}
];
reNormaNormalizedInterpolatedIntegratedYieldEne[\[Epsilon]_]=(p*normalizedInterpolatedIntegratedYieldEne[\[Epsilon]]+q)/.solReNorma;printD@reNormaNormalizedInterpolatedIntegratedYieldEne[minEne];
printD@reNormaNormalizedInterpolatedIntegratedYieldEne[maxEne]
,
Print["\< INFO - renorma - no renorma \>"];
reNormaNormalizedInterpolatedIntegratedYieldEne[\[Epsilon]_]=normalizedInterpolatedIntegratedYieldEne[\[Epsilon]]
];
photonEnergies={};
photonEnergies=w/.FindRoot[
(reNormaNormalizedInterpolatedIntegratedYieldEne[w])==#,{w,(minEne+maxEne)/2,minEne,maxEne}
,WorkingPrecision->MachinePrecision
,PrecisionGoal->7
,AccuracyGoal->7
]&/@RandomReal[{0,1},num];
debugPrintD@MinMax[photonEnergies];
debugPrintD@MinMax[\[Lambda][photonEnergies]];
Print@Histogram@\[Lambda][photonEnergies];
,{InterpolatingFunction::dmval,FindRoot::lstol}];
Return[photonEnergies];
];

(* ---- initialization cell 50 | 3304f833-e5d8-4d5f-b1b9-fb22e2ac9635 ---- *)
(**************************************************************************************************)
(* HERE STEERING AND CHERENKOV YIELD *)
(**************************************************************************************************)
detectorResultsNames0={
"\<CherenkovTAG\>",
"\<nominal \[Lambda]1 = \[Lambda]Min (nm)\>",
"\<nominal \[Lambda]2 = \[Lambda]Max (nm)\>",
"\<wavLenMean0 @emission in WR (nm)\>",
"\<wavLenMedian0 @emission in WR (nm)\>",
"\<refrIndex[\[Lambda]1]\>",
"\<refrIndex[wavLenMean0]\>",
"\<refrIndex[wavLenMedian0]\>",
"\<refrIndex[\[Lambda]2]\>",
"\<whichRICH\>",
"\<radiator\>",
"\<gas radiator cfFromReferenceCavernToRealSystemPT\>",
"\<gas radiator pressure (mbar)\>",
"\<gas radiator temperature (K)\>",
"\<sensor\>",
"\<used radiator path length\>",
"\<meanNRefrPhs\>",
"\<meanNRefrGrp\>",
"\<velPhaseAtMeanWavLen\>",
"\<velGroupAtMeanWavLen\>",
"\<dispersionRefrIndexPhsWavLen\>",
"\<dispersionRefrIndexGrpWavLen\>",
"\<dispersionPhaseVelocityWavLen\>",
"\<dispersionGroupVelocityWavLen\>",
"\<thetaCherenkovSatAtWavLenMean (mrad)\>",
"\<thetaCherenkovSatAtWavLenHgh (mrad)\>",
"\<thetaCherenkovSatAtWavLenLow (mrad)\>",
"\<deltaThetaCherenkovSatAtWavLenExtremes (mrad)\>",
"\<Sin^2[<thetaC>]\>",
"\<emissionYieldEneMeter (#/m)\>",
"\<emissionYieldLamMeter (#/m)\>",
"\<emissionYieldEneTotal (#)\>",
"\<emissionYieldLamTotal (#)\>",
"\<integratedFullYieldPerMeter\>",
"\<integratedFullYield\>",
"\<yield/meter ideal, eff=1, just emission (#/m)\>",
"\<yield/meter raw: YieldCnst*Sin^2[<thetaC>]*\[Delta]E (#/m)\>",
"\<overall fixed efficiency factors product\>",
"\<overall energy integrated PhDetEff (PDE*eV)\>",
"\<overall mean PDE\>",
"\<total real yield in RICH (#)\>",
"\<chrUncertainty (mrad)\>",
"\<energyMedian @detection fully weighted (eV)\>",
"\<wavLenMedian @detection fully weighted (nm)\>",
"\<refrIndex[wavLenMedian]\>",
"\<nZero\>"
};

(* ---- initialization cell 51 | d23c91c7-eb57-fc40-8ca1-063b8b275e78 ---- *)
ClearAll[printRefrIndex,printRefrIndexCore,pri]

printRefrIndexCore[x_]=If[1<=x<=1.1,"\< n-1 : \>"<>ToString[nf[x-1,12,9]],"\<  n  : \>"<>ToString[nf[x,       12,9]]];

printRefrIndex[x_]=If[1<=x<=1.1,Print["\< n-1 : \>",nf[x-1,12,9]],Print["\<  n  : \>",nf[x       ,12,9]]];

pri[x_]=printRefrIndex[x];(*just a short-name*)

SetAttributes[{printRefrIndex,printRefrIndexCore,pri},Listable];

printRefrIndex[theRefrIndex[listOfWavLenSlices]];

pri[1.2];

printRefrIndex[1.0002];

(* ---- initialization cell 52 | ade8c162-badf-274d-8d7b-6670c9fcee72 ---- *)
(*debug for temporary variables: get rid of $dddd*)
Clear[showItTemp,printTempD,debugPrintTempD];
showItTemp[code_]:=Module[{y},Print[First@StringSplit[ToString[Unevaluated[code]],"\<$\>"],"\< = \>",y=code];y]
printTempD[x_]:=showItTemp[x]
debugPrintTempD[input__]:=Module[{},If[debugPrintEnabledFlag,printTempD[input]]]
SetAttributes[{showItTemp,printTempD,debugPrintTempD},HoldAll];

(* ---- initialization cell 53 | f59e0f90-9844-7f4b-98b3-1c43ad5f758b ---- *)
(**************************************************************************************************)
Clear[calcRICHYield];
calcRICHYield[rad_,tmp\[Lambda]1_,tmp\[Lambda]2_,whichRICH_:0,sensor_:"\<ZERO\>",length_:0,numToGenerate_:1000,debug$calcRICHYield_:True,thisNumOfQuantiles_:11]:=Module[{refrIndex,velPhase,velGroup,
\[ScriptCapitalE],\[CapitalLambda],s,wp,a,b,
(*wavLenMedian,wavLenMean,integralSpectrum,*)(* keep as general... TBI *)
theWhichRICH,theRad,theSensor,
dispersionRefrIndexPhsWavLen,dispersionRefrIndexGrpWavLen,
deltaThetaCherenkovSatAtWavLenExtremes,thetaCherenkovSatAtWavLenMean,
thetaCherenkovSatAtWavLenLow,
thetaCherenkovSatAtWavLenHgh,
emissionYieldEneMeter,emissionYieldEneTotal,emissionYieldLamMeter,emissionYieldLamTotal,
meanNRefrPhs,meanNRefrGrp,dispersionPhaseVelocityWavLen,dispersionGroupVelocityWavLen,
lengthRich,
integratedFullYield,integratedFullYieldPerMeter,\[Delta]E,
velPhaseAtMeanWavLen,velGroupAtMeanWavLen,
histoVelLimits,histoVelLimitsGas,
nc1,nc2,
\[Lambda]1,\[Lambda]2,the\[Lambda]1,the\[Lambda]2,(*listQuantiles,*)listOfWavLen,
sampleL,sampleE,
(*theRefrIndexAtLambdaMin,theRefrIndexAtLambdaMean,theRefrIndexAtLambdaMedian,theRefrIndexAtLambdaMax,*)(*cfFromReferenceCavernToRealSystemPT,*)
sinSquaredTheta,
approxEmissionYieldEnePerMeter,
averagePDE,overallEffConstFactor,overallEneIntegratedPhDetEff,
nZero,chrUncertainty,
(*detectorResultsSave,*)
velocitiesHisto,angleChrHistoOne,angleChrHistoBis,angleChrHistoTer,angleChrData,thetaCenterHisto,
defaultNumberOfHistoChannels,numDebugSteps,
epsFine,epsRaw,
thisRichRefrIndexParams
},
(**)
myNotebookInit`bigBanner["\< calcRICHYield - START \>"];
debugPrintEnabledFlag=debug$calcRICHYield;
debugPrint["\< debugPrintEnabledFlag = \>",debugPrintEnabledFlag];
(**)
(*detectorResults*)
(**)
SetOptions[NIntegrate,MaxRecursion->100];
defaultNumberOfHistoChannels=40;
(**)
(*==================================================================================================*)
(*RESET GLOBAL VARIABLES IN detectorResults // HAVE TO BECOME LOCAL*)
(*==================================================================================================*)
wavLenMean=0;(*this should become local, to clean up*)
wavLenMedian=0;(*this should become local, to clean up*)
theRefrIndexAtLambdaMin=0;(*this should become local, to clean up*)
theRefrIndexAtLambdaMedian=0;(*this should become local, to clean up*)
theRefrIndexAtLambdaMean=0;(*this should become local, to clean up*)
theRefrIndexAtLambdaMax=0;(*this should become local, to clean up*)
cfFromReferenceCavernToRealSystemPT=0;(*this should become local, to clean up*)
theRealGasPresMbar=0;(*this should become local, to clean up*)
theRealGasTempKelv=0;(*this should become local, to clean up*)
(**)

epsFine=N[(10)^(-theHighPrecision/3)];(*$MachineEpsilon*)
epsRaw=0.001;
wp=theHighPrecision(*+10*);
(**)
(*==================================================================================================*)
(*which detector*)
theWhichRICH=whichRICH;
(*==================================================================================================*)
(*radiator*)
Print["\<UNDEFINED YET: \n \>",
"\<theRealGasPresMbar (mbar) = \>",nf2@theRealGasPresMbar,"\<\n \>",
"\<theRealGasTempKelv (K)    = \>",nf2@theRealGasTempKelv];
lenTag=Length[StringSplit[rad,"\<-\>"]];
If[(lenTag!=1 )&& (lenTag!=3),
myNotebookInit`bigBanner["\<ERROR - STOP\>"];myNotebookInit`killStop
];
theRad=StringSplit[rad,"\<-\>"][[1]];
If[lenTag==1,
theRealGasPresMbar=referenceCavernPres;
theRealGasTempKelv=referenceCavernTemp
];
If[lenTag==3,
theRealGasPresMbar=ToExpression@StringSplit[rad,"\<-\>"][[2]];
theRealGasTempKelv=ToExpression@StringSplit[rad,"\<-\>"][[3]]
];
cfFromReferenceCavernToRealSystemPT=SetPrecision[(*get rid of meaningless digits*)
gasRefrIndexCorrectionFactorFunction[theRealGasPresMbar,theRealGasTempKelv,referenceCavernPres,referenceCavernTemp],
MachinePrecision
];
(*==================================================================================================*)
(* change the real gas p/T from default to the real one // a bit messy *)
Print["\< NOW DEFINED: \n \>",
"\<theRealGasPresMbar (mbar) = \>",nf2@theRealGasPresMbar,"\<\n \>",
"\<theRealGasTempKelv (K)    = \>",nf2@theRealGasTempKelv];
(*==================================================================================================*)
(*
(*by hand double check*)
g[p1_,p2_,t1_,t2_]=(p2/p1)*(t1/t2);
g[1013.25,980.,273.15,293]
printD@nf2@presSTP;(*mbar*)
printD@nf2@referenceCavernPres;
printD@nf2@theRealGasPresMbar;
ppp={presSTP,referenceCavernPres,theRealGasPresMbar}
printD@nf2@tempSTP;(*K*)
printD@nf2@referenceCavernTemp;
printD@nf2@theRealGasTempKelv;
ttt={tempSTP,referenceCavernTemp,theRealGasTempKelv}
a=g[ppp[[1]],ppp[[3]],ttt[[1]],ttt[[3]]]
a1=g[ppp[[1]],ppp[[2]],ttt[[1]],ttt[[2]]]
a2=g[ppp[[2]],ppp[[3]],ttt[[2]],ttt[[3]]]
a1*a2
*)
(*==================================================================================================*)

printD@nf2@presSTP;(*mbar*)
printD@nf2@referenceCavernPres;
printD@nf2@theRealGasPresMbar;
printD@nf2@tempSTP;(*K*)
printD@nf2@referenceCavernTemp;
printD@nf2@theRealGasTempKelv;
Print["\< gasCorrFactFromSTPToReferenceCavern : \>",nf3@cfFromSTPToReferenceCavern];
Print["\< gasCorrFactToRealFromCavern         : \>",nf3@cfFromReferenceCavernToRealSystemPT];
Print["\< gasCorrFactFull                     : \>",nf3@theFullCf];
(*SENSOR*)
\[Lambda]1:=Round[tmp\[Lambda]1,epsRaw];
\[Lambda]2:=Round[tmp\[Lambda]2,epsRaw];
the\[Lambda]1:=Round[tmp\[Lambda]1];
the\[Lambda]2:=Round[tmp\[Lambda]2];
lengthRich=length;
theSensor=sensor;
\[Delta]E:=\[Epsilon][\[Lambda]1]-\[Epsilon][\[Lambda]2];
(**)
(*==================================================================================================*)
(*==================================================================================================*)
If[whichRICH==1,If[lengthRich==0,lengthRich=nominalLengthRich1]];
If[whichRICH==2,If[lengthRich==0,lengthRich=nominalLengthRich2]];
If[whichRICH==9,If[lengthRich==0,lengthRich=nominalLengthALADDIN]];
If[(whichRICH\[NotEqual]1)&&(whichRICH\[NotEqual]2)&&(whichRICH\[NotEqual]9),
debugPrint["\< RICH = NULL \>"],
If[whichRICH==1,debugPrint["\< RICH  1 \>"]];If[whichRICH==2,debugPrint["\< RICH  2 \>"]];If[whichRICH==9,debugPrint["\< ALADDIN \>" ]]
];
(*--------------------------------------------------------------------------------*)
(* Cherenkov photon yield *)
(*--------------------------------------------------------------------------------*)
refrIndex[\[Lambda]_]:=-1;(* fall-back if calling .... *)
velPhase[\[Lambda]_]:=-1;(* fall-back if calling .... *)
velGroup[\[Lambda]_]:=-1;(* fall-back if calling .... *)
histoVelLimitsGas={0.9970,0.9996,0.000025};
(**)
If[theRad=="\<He\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrHe[\[Lambda]]];
If[lengthRich==0,lengthRich=nominalLengthALADDIN];
histoVelLimits={0.990,1,0.0001};
velPhase[\[Lambda]_]:=vpHe[\[Lambda]];
velGroup[\[Lambda]_]:=vgHe[\[Lambda]]
];
If[theRad=="\<Ne\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrNe[\[Lambda]]];
If[lengthRich==0,lengthRich=nominalLengthALADDIN];
histoVelLimits={0.990,1,0.0001};
velPhase[\[Lambda]_]:=vpNe[\[Lambda]];
velGroup[\[Lambda]_]:=vgNe[\[Lambda]]
];
If[theRad=="\<C4F10\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrC4F10[\[Lambda]]];
histoVelLimits=histoVelLimitsGas;
velPhase[\[Lambda]_]:=vpC4F10[\[Lambda]];
velGroup[\[Lambda]_]:=vgC4F10[\[Lambda]]
];
If[theRad=="\<C1F04\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrC1F04[\[Lambda]]];
histoVelLimits=histoVelLimitsGas;
velPhase[\[Lambda]_]:=vpC1F04[\[Lambda]];
velGroup[\[Lambda]_]:=vgC1F04[\[Lambda]]
];
If[theRad=="\<C1O02\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrC1O02[\[Lambda]]];
histoVelLimits=histoVelLimitsGas;
velPhase[\[Lambda]_]:=vpC1O02[\[Lambda]];
velGroup[\[Lambda]_]:=vgC1O02[\[Lambda]];
];
If[theRad=="\<FQrtz\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrFQrtz[\[Lambda]]];
histoVelLimits={0.5,1.0,0.0125};
velPhase[\[Lambda]_]:=vpFQrtz[\[Lambda]];
velGroup[\[Lambda]_]:=vgFQrtz[\[Lambda]];
If[lengthRich==0,lengthRich=10];
];
If[theRad=="\<AERGL\>",
refrIndex[\[Lambda]_]:=precisionify[nRefrAergl[\[Lambda]]];
histoVelLimits={0.95,1.0,0.001};
velPhase[\[Lambda]_]:=vpAergl[\[Lambda]];
velGroup[\[Lambda]_]:=vgAergl[\[Lambda]];
If[lengthRich==0,lengthRich=10];
];
If[theRad=="\<AIR\>",(*TO DO*)
refrIndex[\[Lambda]_]:=precisionify[nRefrAir[\[Lambda]]];
histoVelLimits=histoVelLimitsGas;
velPhase[\[Lambda]_]:=vpAir[\[Lambda]];
velGroup[\[Lambda]_]:=vgAir[\[Lambda]];
If[lengthRich==0,lengthRich=1000];
];
(**)
Print["\< radiator       = \>",theRad];





Print["\< refrIndex[\[Lambda]]   = \>",nf[refrIndex[\[Lambda]],12,8]];



(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\<refractive index business - determine one-pole Sellmeier parameters\>"];
(*--------------------------------------------------------------------------------*)

thisRichRefrIndexParams=First@NSolve[(refrIndex[\[Lambda]]  ==1+((a)/(((1)/((b)^(2)))-((1)/((\[Lambda])^(2)))))/.\[Lambda]->\[Lambda]MinRef)&&(refrIndex[\[Lambda]]  ==1+((a)/(((1)/((b)^(2)))-((1)/((\[Lambda])^(2)))))/.\[Lambda]->\[Lambda]MaxRef),{a,b}];
printD@thisRichRefrIndexParams;
If[
(refrIndex[\[Lambda]]  ==1+((a)/(((1)/((b)^(2)))-((1)/((\[Lambda])^(2)))))/.thisRichRefrIndexParams/.\[Lambda]->(\[Lambda]MinRef+\[Lambda]MaxRef)/2)==True,
Print["\<parameters confirmed : thisRichRefrIndexParams = \>",thisRichRefrIndexParams];

,
Print["\<parameters NOT confirmed : thisRichRefrIndexParams - possibly more than one pole Sellemeier ???? \>"];
];
Print["\< must be all True to within numerical rounding --- \>",Table[refrIndex[\[Lambda]]  ==1+((a)/(((1)/((b)^(2)))-((1)/((\[Lambda])^(2)))))/.thisRichRefrIndexParams,{\[Lambda],\[Lambda]MinRef,\[Lambda]MaxRef,100}]];




(**)
refrIndexGrp[\[Lambda]_]:=1/velGroup[\[Lambda]];
refrIndexPhs[\[Lambda]_]:=refrIndex[\[Lambda]];(* Use refrIndex as default but duplicate to full name *)
(**)
theRadiator=theRad;(* Used outside this routine // global *)
theRefrIndex[\[Lambda]_]=refrIndex[\[Lambda]];(* theRefrIndex: used outside this routine // global // to check *)
thePhotonSpeed[\[Lambda]_]:=velGroup[\[Lambda]];
(**)
(* average waveln, exact emission spectrum *)
wavLenMean=Round[NIntegrate[\[CapitalLambda]*(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}]/NIntegrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}],epsRaw];
(**)
velPhaseAtMeanWavLen=Round[velPhase[wavLenMean],epsFine];
velGroupAtMeanWavLen=Round[velGroup[wavLenMean],epsFine];
(**)
(* integrate in energy per meter *)
emissionYieldEneMeter=Round[theChrYieldConstant*NIntegrate[1-((1/refrIndex[\[Lambda][\[ScriptCapitalE]]]))^(2),{\[ScriptCapitalE],\[Epsilon][\[Lambda]2],\[Epsilon][\[Lambda]1]}],epsFine];
Print["\< radiator-only #/meter energy integral (ideal, eff=1) = \>",nf[emissionYieldEneMeter,7,2]];
(* integrate in energy total *)
emissionYieldEneTotal=Round[theChrYieldConstant*NIntegrate[1-((1/refrIndex[\[Lambda][\[ScriptCapitalE]]]))^(2),{\[ScriptCapitalE],\[Epsilon][\[Lambda]2],\[Epsilon][\[Lambda]1]}]*lengthRich/1000,epsFine];
debugPrint["\< radiator-only # total energy integral (ideal, eff=1) = \>",nf[emissionYieldEneTotal,7,2]];
(* integrate in waveln per meter *)
emissionYieldLamMeter=Round[theChrYieldConstant*theConstantWavLenFromToEnergy*NIntegrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}],epsFine];
Print["\< radiator-only #/meter waveln integral (ideal, eff=1) = \>",nf[emissionYieldLamMeter,7,2]];
(* integrate in waveln total *)
emissionYieldLamTotal=Round[theChrYieldConstant*theConstantWavLenFromToEnergy*NIntegrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}]*lengthRich/1000,epsFine];
debugPrint["\< radiator-only # total waveln integral (ideal, eff=1) = \>",nf[emissionYieldLamTotal,7,2]];
(* Quantiles in spectrum: NB median != mean !!! *)
(* NIntegrate with non-numerical gives error: delay with := and make sure using numercals only later *)
(*integralSpectrum0[s_]:=NIntegrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,s},MaxRecursion->200,WorkingPrecision->wp,AccuracyGoal->7];*)
(* use -eps to avoid trouble with undefined integral results TBF !@#$% NOT WORKING *)
(*g[s_]:=Chop@FullSimplify[Integrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,s}],\[Lambda]1<=\[CapitalLambda]<=s];*)
(**)
Clear[integralSpectrum,integralSpectrumRaw,analyticIntegratedSpectrum,numericIntegratedSpectrum];
(**)
integralSpectrumRaw[s_]=Re@Chop[FullSimplify[Integrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1-epsFine,s}],(\[Lambda]1<=\[CapitalLambda]<=s)&&(s>\[Lambda]1-1)]];
(**)
analyticIntegratedSpectrum=Re@Chop[integralSpectrumRaw[\[Lambda]2]];
debugPrint["\<analytic integrated spectrum      \>",ScientificForm[analyticIntegratedSpectrum,11]];
(**)
numericIntegratedSpectrum=NIntegrate[(1-((1/refrIndex[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1-epsFine,\[Lambda]2},WorkingPrecision->wp,MaxRecursion->1000];
debugPrint["\<numeric integrated spectrum       \>",ScientificForm[numericIntegratedSpectrum,11]];
(**)
integralSpectrum[s_]=Re@Chop[integralSpectrumRaw[s]/analyticIntegratedSpectrum];
(*
debugPrint["\<integralSpectrumRaw[s]                          \>",integralSpectrumRaw[s]];
debugPrint["\<integralSpectrum[s]                             \>",integralSpectrum[s]];
debugPrint["\< ComplexExpand[integralSpectrum[s]]          =\n\>",ScientificForm[#,3]&@ComplexExpand[integralSpectrum[s]]];
debugPrint["\< ReIm[integralSpectrum[s]]                   =\n\>",ScientificForm[#,3]&@ReIm[integralSpectrum[s]]];debugPrint["\< Im[integralSpectrum[s]]                     =\n\>",ScientificForm[#,3]&@Im[integralSpectrum[s]]];debugPrint["\< Re[integralSpectrum[s]]                     =\n\>",ScientificForm[#,3]&@Re[integralSpectrum[s]]];debugPrint["\< ComplexExpand[ReIm[integralSpectrum[s]]]    =\n\>",ScientificForm[#,3]&@ComplexExpand[ReIm[integralSpectrum[s]]]];
*)
(**)
(*thisNumOfQuantiles;*)(* MUST BE ODD *)
Print["\<thisNumOfQuantiles      \>",thisNumOfQuantiles];
If[EvenQ[thisNumOfQuantiles],
Print["\<thisNumOfQuantiles   even   \>",thisNumOfQuantiles];
thisNumOfQuantiles=thisNumOfQuantiles+1      ,
Print["\<thisNumOfQuantiles  odd    \>",thisNumOfQuantiles]
];
Print["\<thisNumOfQuantiles      \>",thisNumOfQuantiles];
listQuantiles=Take[Table[w,{w,0,1,1/(thisNumOfQuantiles-1)}],{2,thisNumOfQuantiles-1}];
Print["\<listQuantiles    \>",listQuantiles];
listOfEqualPureEmissionYieldWavLenSlices:= 
Re[Chop[
s/.(FindRoot[SetPrecision[(integralSpectrum[s]-#),wp],{s,(\[Lambda]1+\[Lambda]2)/2,\[Lambda]1,\[Lambda]2},
WorkingPrecision->wp,(* !@#$% TO FIX: FAILS with -> wp*)
AccuracyGoal->7,
PrecisionGoal->7,
MaxIterations->10000]
&/@listQuantiles)
]];
listOfEqualPureEmissionYieldWavLenSlices=Round[Join[{\[Lambda]1},listOfEqualPureEmissionYieldWavLenSlices,{\[Lambda]2}],epsRaw];
debugPrintD@nf@listOfEqualPureEmissionYieldWavLenSlices;
(**)
wavLenMedian=listOfEqualPureEmissionYieldWavLenSlices[[(thisNumOfQuantiles+1)/2]];
theRefrIndexAtLambdaMin=Max[refrIndex[\[Lambda]1],refrIndex[\[Lambda]2]];(*assume monotone refrIndex versus \[Lambda]*)
theRefrIndexAtLambdaMax=Min[refrIndex[\[Lambda]1],refrIndex[\[Lambda]2]];(*assume monotone refrIndex versus \[Lambda]*)
theRefrIndexAtLambdaMean=refrIndex[wavLenMean];
theRefrIndexAtLambdaMedian=refrIndex[wavLenMedian];
(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\<debug units of measure and refractive index\>"];
(*--------------------------------------------------------------------------------*)
Print["\< \[Lambda]1  : \>",\[Lambda]1];
Print["\< refrIndex at \[Lambda]1      : \>",nf[theRefrIndexAtLambdaMin,8,7,2]];
Print["\< refrIndex at \[Lambda]mean   : \>",nf[theRefrIndexAtLambdaMean,8,7,2]];
Print["\< refrIndex at \[Lambda]median : \>",nf[theRefrIndexAtLambdaMedian,8,7,2]];
Print["\< refrIndex at \[Lambda]2      : \>",nf[theRefrIndexAtLambdaMax,8,7,2]];
Print["\< \[Lambda]2  : \>",\[Lambda]2];
(**)
numDebugSteps=10;
printRefrIndex[refrIndex[listOfWavLenSlices]];
Print@TableForm@Table[{nf@k,nf[refrIndex[k],12,8]},{k,\[Lambda]1,\[Lambda]2,Abs[\[Lambda]2-\[Lambda]1]/numDebugSteps}];
(*--------------------------------------------------------------------------------*)
miniBanner["\<debug integral spectrum\>"];
(*--------------------------------------------------------------------------------*)
debugPrint[Plot[integralSpectrum[s],{s,\[Lambda]1,\[Lambda]2}]];
debugPrint[TableForm[Table[{nf@s,nf3@integralSpectrum[s]},{s,\[Lambda]1,\[Lambda]2,Abs[\[Lambda]2-\[Lambda]1]/numDebugSteps}]]];
(**)
(*weight on refrIndexPhs*)
meanNRefrPhs=Round[NIntegrate[
refrIndexPhs[\[CapitalLambda]]*(1-((1/refrIndexPhs[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}]/NIntegrate[(1-((1/refrIndexPhs[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}],epsFine];
(*also for group velocity weight on refrIndexPhs!!!*)
meanNRefrGrp=Round[NIntegrate[
refrIndexGrp[\[CapitalLambda]]*(1-((1/refrIndexPhs[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}]/NIntegrate[(1-((1/refrIndexPhs[\[CapitalLambda]]))^(2))/(\[CapitalLambda])^(2),{\[CapitalLambda],\[Lambda]1,\[Lambda]2}],epsFine];
dispersionRefrIndexPhsWavLen=Round[Abs[refrIndexPhs[\[Lambda]1]-refrIndexPhs[\[Lambda]2]]/(\[Lambda]2-\[Lambda]1),epsFine];
dispersionRefrIndexGrpWavLen=Round[Abs[refrIndexGrp[\[Lambda]1]-refrIndexGrp[\[Lambda]2]]/(\[Lambda]2-\[Lambda]1),epsFine];
dispersionPhaseVelocityWavLen=Round[Abs[velPhase[\[Lambda]2]-velPhase[\[Lambda]1]]/velPhase[wavLenMean],epsFine];
dispersionGroupVelocityWavLen=Round[Abs[velGroup[\[Lambda]2]-velGroup[\[Lambda]1]]/velGroup[wavLenMean],epsFine];
thetaCherenkovSatAtWavLenMean=Round[1000*ArcCos[1/refrIndex[wavLenMean]],epsRaw];
(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\<debug angles\>"];
(*--------------------------------------------------------------------------------*)
halfOpenAngleMRad=thetaCherenkovSatAtWavLenMean;
printD@halfOpenAngleMRad;
(**)
thetaCherenkovSatAtWavLenLow=Round[1000*(ArcCos[1/refrIndex[\[Lambda]1]]),epsRaw];
thetaCherenkovSatAtWavLenHgh=Round[1000*(ArcCos[1/refrIndex[\[Lambda]2]]),epsRaw];
deltaThetaCherenkovSatAtWavLenExtremes=Round[1000*(ArcCos[1/refrIndex[\[Lambda]1]]-ArcCos[1/refrIndex[\[Lambda]2]]),epsRaw];
(*debugPrintTempD[nf[deltaThetaCherenkovSatAtWavLenExtremes,7,2]];*)
debugPrintTempD[thetaCherenkovSatAtWavLenHgh];
debugPrintTempD[thetaCherenkovSatAtWavLenLow];
(**)
(*--------------------------------------------------------------------------------*)
(* calcDetectedPhotons --- photon transport and sensor PDE *)
(*--------------------------------------------------------------------------------*)
resultsCalcDetectedPhotons=calcDetectedPhotons[whichRICH,sensor,\[Epsilon][\[Lambda]2],\[Epsilon][\[Lambda]1],0.1,debug$calcRICHYield];
If[resultsCalcDetectedPhotons===$Failed,Return[$Failed]];
Do[
debugPrintD[resultsCalcDetectedPhotons[[i]]];
,{i,1,Length@resultsCalcDetectedPhotons}
];
detectorResultsNames:=Join[
detectorResultsNames0,
{"\<theIntegratedFullYieldEne\>","\<thisTotEff\>","\<overallIntegratedPDEEne\>"},
allTheEfficiencies[sensor][[1]]
];
(**)
theCherenkovTag="\<TAG\>"<>"\<-\>"<>rad<>"\<-\>"<>ToString[the\[Lambda]1]<>"\<-\>"<>ToString[the\[Lambda]2]<>"\<-R\>"<>ToString[theWhichRICH]<>"\<-\>"<>theSensor<>"\<-\>"<>ToString[lengthRich];
(**)
detectorResults:=Flatten@Join[{
theCherenkovTag,
\[Lambda]1,\[Lambda]2,
wavLenMean,(*this should become local, to clean up*)
wavLenMedian,(*this should become local, to clean up*)
theRefrIndexAtLambdaMin,(*this should become local, to clean up*)
theRefrIndexAtLambdaMean,(*this should become local, to clean up*)
theRefrIndexAtLambdaMedian,(*this should become local, to clean up*)
theRefrIndexAtLambdaMax,(*this should become local, to clean up*)
theWhichRICH,theRad,
cfFromReferenceCavernToRealSystemPT,(*this should become local, to clean up*)
theRealGasPresMbar,(*this should become local, to clean up*)
theRealGasTempKelv,(*this should become local, to clean up*)
theSensor,lengthRich,
meanNRefrPhs,meanNRefrGrp,
velPhaseAtMeanWavLen,velGroupAtMeanWavLen,
dispersionRefrIndexPhsWavLen,dispersionRefrIndexGrpWavLen,
dispersionPhaseVelocityWavLen,dispersionGroupVelocityWavLen,
thetaCherenkovSatAtWavLenMean,
thetaCherenkovSatAtWavLenHgh,
thetaCherenkovSatAtWavLenLow,
deltaThetaCherenkovSatAtWavLenExtremes,
sinSquaredTheta,
emissionYieldEneMeter,emissionYieldLamMeter,
emissionYieldEneTotal,emissionYieldLamTotal,
integratedFullYieldPerMeter,integratedFullYield,
emissionYieldEneMeter(* duplicate OK to compare *),
approxEmissionYieldEnePerMeter,
overallEffConstFactor,
overallEneIntegratedPhDetEff ,
averagePDE,
integratedFullYield,
chrUncertainty,
medianDetEnergy,(*this should become local, to clean up*)
medianDetWavLen,(*this should become local, to clean up*)
Round[refrIndex[medianDetWavLen],epsFine],
nZero
},
resultsCalcDetectedPhotons
];
(**)
Print["\< length of the Rich                  \>",lengthRich];
integratedFullYieldPerMeter=resultsCalcDetectedPhotons[[1]];
Print["\< integratedFullYieldPerMeter \>",integratedFullYieldPerMeter];
integratedFullYield=integratedFullYieldPerMeter*lengthRich/1000;
Print["\< integratedFullYield         \>",integratedFullYield];
sinSquaredTheta:=(Sin[thetaCherenkovSatAtWavLenMean/1000])^(2);
approxEmissionYieldEnePerMeter:=theChrYieldConstant*sinSquaredTheta*\[Delta]E;
averagePDE:=integratedFullYieldPerMeter/emissionYieldLamMeter;
overallEffConstFactor:=If[Length@resultsCalcDetectedPhotons>=3,resultsCalcDetectedPhotons[[2]],0];
overallEneIntegratedPhDetEff :=If[Length@resultsCalcDetectedPhotons>=3,resultsCalcDetectedPhotons[[3]],0];
(**)
debugPrintTempD@sinSquaredTheta;
debugPrintTempD@approxEmissionYieldEnePerMeter;
debugPrintTempD@averagePDE;
debugPrintTempD@overallEffConstFactor;
debugPrintTempD@overallEneIntegratedPhDetEff;
nZero=(integratedFullYield/(lengthRich/1000)/ sinSquaredTheta );
Print["\< nZero                       \>",nZero];
(**)
listOfWavLen=waveln[generatePhotonEnergy[numToGenerate,\[Epsilon][\[Lambda]2],\[Epsilon][\[Lambda]1]]];
miniBanner["\< test RandomVariate \>"];
Print@Histogram[listOfWavLen,PlotLabel->"\< from generatePhotonEnergy\>"];
sampleE=RandomVariate[ProbabilityDistribution[fE[\[Epsilon]],{\[Epsilon],\[Epsilon][\[Lambda]2],\[Epsilon][\[Lambda]1]},Method->"\<Normalize\>"],Round[numToGenerate/10]];
Print@Histogram[sampleE,PlotLabel->"\< RandomVariate - energy\>"];
sampleL=RandomVariate[ProbabilityDistribution[fL[\[Lambda]],{\[Lambda],\[Lambda]1,\[Lambda]2},Method->"\<Normalize\>"],Round[numToGenerate/10]];
Print@Histogram[sampleL,PlotLabel->"\< RandomVariate - wavlen\>"];
(**)
Print[velocitiesHisto=Histogram[{Map[velGroup[#]&,listOfWavLen],Map[velPhase[#]&,listOfWavLen]},
histoVelLimits,
"\<Probability\>",
PlotLabel->"\<photon velocities\>",
Ticks->{Automatic,None},
AxesLabel->{"\<v/c\>","\<\>"}]];
Export["\<C:\\TEMP\\photon-velocities-\>"<>fileNameTag<>"\<.pdf\>",velocitiesHisto,"\<PDF\>"];
(**)
Print[velocitiesHisto=Histogram[{Map[velGroup[#]&,listOfWavLen],Map[velPhase[#]&,listOfWavLen]},
defaultNumberOfHistoChannels,
"\<Probability\>",
PlotLabel->"\<photon velocities - free histo limits \>",
Ticks->{Automatic,None},
AxesLabel->{"\<v/c\>","\<\>"}
]
];
(**)
thetaCenterHisto=(thetaCherenkovSatAtWavLenHgh+thetaCherenkovSatAtWavLenLow)/2;

angleChrData=1000*chrnkvAngle[1,999999,listOfWavLen];
descriptivestatistics[angleChrData];
(*Print[descriptivestatistics[angleChrData]];*)
(*Print[lgd];*)
(**)
(* plot first time..... *)
Print[angleChrHistoOne=Histogram[angleChrData,
{thetaCenterHisto-2,thetaCenterHisto+1,0.05},
"\<Probability\>",
PlotLabel->"\< Cherenkov angle distribution \>",
Ticks->{Table[k,{k,0,100,0.5}],None},
AxesLabel->{"\<\!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\)\>","\<\>"}
(*,Epilog->lgd*)
]
];
(*mandatory to call descriptivestatistics before using lgd //WRONG correct lgd*)
Export["\<C:\\TEMP\\angle-Chr-one-\>"<>fileNameTag<>"\<.pdf\>",angleChrHistoOne,"\<PDF\>"];
(**)
(* repeat plot second time to debug..... *)
descriptivestatistics[angleChrData];
(*Print[descriptivestatistics[angleChrData]];*)
(*Print[lgd];*)
Print[angleChrHistoBis=Histogram[angleChrData,
defaultNumberOfHistoChannels,
"\<Probability\>",
PlotLabel->"\< Cherenkov angle distribution - free histo limits \>",
AxesLabel->{"\<\!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\)\>","\<\>"},
Ticks->{Table[k,{k,0,100,0.5}],None}
(*,Epilog->lgd*)
]
];
Export["\<C:\\TEMP\\angle-Chr-bis-\>"<>fileNameTag<>"\<.pdf\>",angleChrHistoBis,"\<PDF\>"];
(*mandatory to call descriptivestatistics before using lgd //WRONG correct lgd*)
(**)
(* repeat plot third time to debug..... *)
angleChrHistoTer=First@displayHistoStats[angleChrData,
{thetaCenterHisto-2,thetaCenterHisto+1,0.05},
"\<Probability\>",
AxesLabel->{"\<\!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\)\>","\<\>"},
Ticks->{Table[k,{k,0,100,0.5}],None},
PlotLabel->fileNameTag
];(* with second options it does not work*)
Export["\<C:\\TEMP\\angle-Chr-ter-\>"<>fileNameTag<>"\<.pdf\>",angleChrHistoTer,"\<PDF\>"];
(**)
chrUncertainty=Round[StandardDeviation[angleChrData],epsRaw];
printTempD@chrUncertainty;
(**)
(*--------------------------------------------------------------------------------*)
(*--------------------------------------------------------------------------------*)
plotCherenkovAngleChromaticLimits[whichRICH,theRad];
(*--------------------------------------------------------------------------------*)
myNotebookInit`bigBanner["\< calcRICHYield - SUMMARY RESULTS - FIRST list \>"];
Print[(*"\< detectorResultsNames \n \>",*)TableForm[Transpose[{detectorResultsNames,detectorResults}],TableSpacing->{1,2},TableAlignments->{Center}]];
Export["\<C:\\TEMP\\rich-detector-data-\>"<>fileNameTag<>"\<.txt\>",TableForm@Transpose[{detectorResultsNames,detectorResults}],"\<Table\>"];
(**)
myNotebookInit`bigBanner["\< calcRICHYield - SUMMARY RESULTS - ANOTHER \>"];
nc1=15;
nc2=8;
(**)
Print["\< whichRICH                                              \>","\<RICH\>"<>ToString[Round[whichRICH]]];Print["\< rad                                                    \>",theRad];
Print["\< real gas pressure (mbar)                               \>",theRealGasPresMbar];
Print["\< real gas temperature (K)                               \>",theRealGasTempKelv];
Print["\< cavern reference nominal gas pressure (mbar)           \>",referenceCavernPres];
Print["\< cavern reference nominal gas temperature (K)           \>",referenceCavernTemp];
Print["\< cfFromReferenceCavernToRealSystemPT : (p,T)            \>",nf[cfFromReferenceCavernToRealSystemPT,nc1,nc2]];
Print["\< rad length (mm)                                        \>",lengthRich];Print["\< sensor                                                 \>",sensor];Print["\< \[Lambda]/\[Epsilon] (1)                               \>","\<\[Lambda]1(min)=\>",nf@\[Lambda]1,"\< -> \[Epsilon][\[Lambda]2](max)=\>",nf@\[Epsilon][\[Lambda]2]];Print["\< \[Lambda]/\[Epsilon] (2)                               \>","\<\[Lambda]2(max)=\>",nf@\[Lambda]2,"\< -> \[Epsilon][\[Lambda]1](min)=\>",nf@\[Epsilon][\[Lambda]1]];Print["\< energy range                                           \>",nf[\[Delta]E,nc1,nc2],"\< (eV)\>"];
Print["\< wavLenNominalMean                                      \>",nf[wavLenMean,nc1,nc2]];
Print["\< wavLenNominalMedian                                    \>",nf[wavLenMedian,nc1,nc2]];
Print["\< listOfEqualPureEmissionYieldWavLenSlices               \>",nf[listOfEqualPureEmissionYieldWavLenSlices,nc1,nc2]];
Print["\< refrIndex[\[Lambda]1]                                  (n-1)     \>",nf[refrIndex[\[Lambda]1]-1,8,1,2]];Print["\< refrIndex[wavLenNominalMean]                       (n-1)     \>",nf[refrIndex[wavLenMean]-1,8,1,2]];Print["\< refrIndex[wavLenNominalMedian]                     (n-1)     \>",nf[refrIndex[wavLenMedian]-1,8,1,2]];Print["\< refrIndex[\[Lambda]2]                                  (n-1)     \>",nf[refrIndex[\[Lambda]2]-1,8,1,2]];
Print["\< mean refrIndex of phase velo                           \>",nf[meanNRefrPhs,8,1,2]];Print["\< mean refrIndex of group velo                           \>",nf[meanNRefrGrp,8,1,2]];Print["\< velPhase[wavLenMean]                                   \>",nf[velPhaseAtMeanWavLen,nc1,nc2+4]];Print["\< velGroup[wavLenMean]                                   \>",nf[velGroupAtMeanWavLen,nc1,nc2+4]];Print["\< dispersionRefrIndexPhsWavLen                           \>",nf[dispersionRefrIndexPhsWavLen,nc1,nc2]];Print["\< dispersionRefrIndexGrpWavLen                           \>",nf[dispersionRefrIndexGrpWavLen,nc1,nc2]];Print["\< dispersionPhaseVelocityWavLen                          \>",nf[dispersionPhaseVelocityWavLen,nc1,nc1,nc2]];Print["\< dispersionGroupVelocityWavLen                          \>",nf[dispersionGroupVelocityWavLen,nc1,nc1,nc2]];Print["\< thetaCherenkovSatAtWavLenMean (mrad)                   \>",nf[thetaCherenkovSatAtWavLenMean,nc1,nc2]];Print["\< Sin[\!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\)[<\[Lambda]>]\!\(\*SuperscriptBox[\(]\), \(2\)]\)                               \>",nf[sinSquaredTheta,nc1,nc2+6]];
Print["\< thetaCherenkovSatAtWavLenHgh                           \>",nf[thetaCherenkovSatAtWavLenHgh,nc1,nc2]];Print["\< thetaCherenkovSatAtWavLenLow                           \>",nf[thetaCherenkovSatAtWavLenLow,nc1,nc2]];Print["\< deltaThetaCherenkovSatAtWavLenExtremes                 \>",nf[deltaThetaCherenkovSatAtWavLenExtremes,nc1,nc2]];
Print["\< approx emission yield/meter ideal (eff=1) K*Sin[\!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\)\!\(\*SuperscriptBox[\(]\), \(2\)]\)*\[Delta]E:     \>",nf[approxEmissionYieldEnePerMeter,nc1,nc2]];
Print["\< calculated emission yield/meter ideal (eff=1):         \>",nf[emissionYieldLamMeter,nc1,nc2]];
Print["\< overall efficiency wave-length independent factor      A  \>",nf[overallEffConstFactor,nc1,nc2]];Print["\< overall integrated: yield * spectral response, in PDE*eV  B  \>",nf[overallEneIntegratedPhDetEff,nc1,nc2]];Print["\< overall integrated ideal efficiency=1 in PDE*eV        C  \>",nf[\[Delta]E,nc1,nc2]];Print["\< average overall PDE                                 = A*B/C  \>",nf[averagePDE,nc1,nc2]];
Print["\< the nZero                                              \>",nf[nZero,nc1,3]];
Print["\< total real yield/meter in RICH                         \>",nf[integratedFullYieldPerMeter,nc1,nc2-2]];Print["\< total real yield in RICH                               \>",nf[integratedFullYield,nc1,nc2-2]];
Print["\< chromatic uncertainty                                  \>",nf[chrUncertainty,nc1,3]];
(**)
(*myNotebookInit`bigBanner["\< result yield data array: \>"];
Print[TableForm@detectorResults];*)
(**)
debugPrint[TableForm[
Join[Transpose[{detectorResults}],{{"\<|===================|\>"}}],TableAlignments->Center,TableHeadings->{detectorResultsNames,{"\< present run results\>","\<previous run results\>"}}
]
];
allDetectorResults[theCherenkovTag]=detectorResults;
(**)
miniBanner["\< calcRICHYield - END \>"];
(**)
Return[detectorResults]
];
(*Save["\<calcRICHYield.m\>",{calcRICHYield}]*)

(* ---- initialization cell 54 | 56e217f4-23a1-7049-883a-f7d3d40f4907 ---- *)
(**************************************************************************************************)
(*HERE PER METER: THERE IS NO PATH LENGTH HERE*)
Clear[calcDetectedPhotons];
calcDetectedPhotons[whichRICH_,sensor_,minEne_:1.5,maxEne_:6.2,deltaEne_:0.1,debug$calcDetectedPhotons_:True]:=Module[{
rad,refrIndex,sE,sL,s,minLam,maxLam,minEne0,maxEne0,minLam0,maxLam0,
(*pdeEffEnergyData,pdeEffWavLenData,*)
(*thisGraphicsInset,thisGraphicsInsetText,*)
plotPdeEffEnergyData,plotPdeEffWavLenData,
pdeEffEnergyFunction,pdeEffWavLenFunction,
plotPdeEffEnergyFunction,plotPdeEffWavLenFunction,
plotSinSquaredThetaSatEnergy,plotSinSquaredThetaSatWavLen,sinSquaredThetaSatEnergy,sinSquaredThetaSatWavLen,plotTotYieldEnergy,plotTotYieldWavLen,plotThetaCEnergy,plotThetaCWavLen,
(*gE,gL,*)
(*fE,fL,*)
theIntegratedFullYieldEne,theIntegratedFullYieldLam,
plotInterpolatedIntegratedYieldEne,plotInterpolatedIntegratedYieldLam,
plotNormalizedInterpolatedIntegratedYieldEne,plotNormalizedInterpolatedIntegratedYieldLam,
deltaEneNIntegration,deltaLamNIntegration,
thisTotEff,
numBins,debugPrintEnabledFlagSave,overallIntegratedPDEEne,overallIntegratedPDELam,
localHisto,theStack,wp,tmpRes,
epsFine,epsRaw
},
(**)
myNotebookInit`bigBanner["\< calcDetectedPhotons - START \>"];
miniBanner["\< HERE EVERYTHING AFTER EMISSION UP TO FINAL DETECTION \>"];
miniBanner["\< This should be the *detect* function: radiation is already produced before, by calcRICHYield yield \>"];
(*
Print["\<*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*\>"];
Print["\< CALLING PARAMETERS : \>",theStack=First[Stack[_]]];
myNotebookInit`bigBanner["\< DO NOT USE SINGULARLY --- ONLY INTERNALLY CALLED BY calcRICHYield \>"];
(*BREAKS EVERYTHING????*)
Print["\< >>>>>>>>>>>> \>",StringTake[ToString@theStack,13]];
Print["\< >>>>>>>>>>>> \>",theStack];
Print["\< >>>>>>>>>>>> \>",theStack[[1]]];
If[StringTake[ToString@theStack,13]<>"\<calcRICHYield\>", 
killStop,
myNotebookInit`bigBanner["\< calcRICHYield caller : ok - go on \>"]
];
Print["\<*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*\>"];
*)
debugPrintEnabledFlag=debug$calcDetectedPhotons;
printD@debugPrintEnabledFlag;
epsFine=N[(10)^(-theHighPrecision/3)];(*$MachineEpsilon*)
epsRaw=0.001;
wp=theHighPrecision(*+10*);
(**)
(*
(* !@#$% keep here to recalculate tags: needed????*)
thisGraphicsInset:=Inset[Framed[Style[thisGraphicsInsetText,15],Background->LightYellow],Scaled[{1,1}],{0.99,0.99}];
SetOptions[Plot,ImageSize->Large];
SetOptions[ListPlot,ImageSize->Large];
SetOptions[LogPlot,ImageSize->Large];*)
SetOptions[{LogPlot,Plot,Graphics,ListPlot,Histogram},Epilog->thisGraphicsInset];

(**)
refrIndex[\[Lambda]_]:=theRefrIndex[\[Lambda]];
rad:=theRadiator<>"\<-\>"<>ToString[theRealGasPresMbar]<>"\<-\>"<>ToString[theRealGasTempKelv];
Print["\< whichRICH = \>",whichRICH];
Print["\< sensor    = \>",sensor];
Print["\< rad       = \>",rad];
Print["\< \[Lambda]2 (max)  = \>",\[Lambda][minEne],"\< <<<---     \[Epsilon] (min)  = \>",minEne];
Print["\< \[Lambda]1 (min)  = \>",\[Lambda][maxEne],"\< <<<---     \[Epsilon] (max)  = \>",maxEne];
Print["\< gasRefrIndexCorrectionFactor  = \>",cfFromReferenceCavernToRealSystemPT];
(**)
fileNameTagRichRad="\<RICH\>"<>ToString[whichRICH]<>"\<-\>"<>ToString[rad];
Print[fileNameTagRichRad];
Print[fileNameShortTag="\<RICH\>"<>ToString[whichRICH]<>"\<-\>"<>ToString[rad]<>"\<-\>"<>ToString[sensor]];
Print[fileNameTag="\<RICH\>"<>ToString[whichRICH]<>"\<-\>"<>ToString[rad]<>"\<-\>"<>ToString[sensor]<>"\<-\>"<>ToString[Round@\[Lambda][maxEne]]<>"\<-\>"<>ToString[Round@\[Lambda][minEne]]];
If[(maxEne-minEne)<0,Print["\<ERROR\>"];Return[$Failed]];

miniBanner["\< USE ENERGY NOT WavLen TO AVOID JACOBIANS \>"];
miniBanner["\< Temporarily disable in routine: InterpolatingFunction warnings \>"];
Quiet[(*Off[NIntegrate::ncvb];
Off[NIntegrate::precw];*)
(**)
(*minEne0=Min[1.,minEne];(*large range extremum for interpolation*)*)
(*maxEne0=Max[7.,maxEne];(*large range extremum for interpolation*)*)
minEne0=1;(*large range extremum for interpolation*)
maxEne0=7;(*large range extremum for interpolation*)
(*minLam0=\[Lambda][maxEne0];(*large range extremum for interpolation*)*)
(*maxLam0=\[Lambda][minEne0];(*large range extremum for interpolation*)*)
minLam0=150;(*large range extremum for interpolation*)
maxLam0=750;(*large range extremum for interpolation*)
minLam=\[Lambda][maxEne];(*real WR*)
maxLam=\[Lambda][minEne];(*real WR*)
(**)
If[
(sensor!="\<UV\>")&&
(sensor!="\<UVSE\>")&&
(sensor!="\<BS\>")&&
(sensor!="\<BSSE\>")&&
(sensor!="\<ZERO\>")&&
(sensor!="\<MAPMTOLD22\>")&&
(sensor!="\<LAPPDTM\>")&&
(sensor!="\<MAPMT22\>")&&
(sensor!="\<MAPMT22s\>")&&
(sensor!="\<MAPMT22l\>")&&
(sensor!="\<SIPMFBK\>")&&
(sensor!="\<MPPCHPK\>")&&
(sensor!="\<TB2021A\>"),
Print["\<Choose a sensor!\>"];myNotebookInit`killStop
];
(*Efficiency factors a priori depend on whichRICH rad sensor*)
(**)
(*--------------------------------------------------------------------------------*)
(*--------------------------------------------------------------------------------*)
(* HERE:everything causing photon losses as just a constant factor *)
(* many have to be better calculated as energy dependent *)
(*--------------------------------------------------------------------------------*)
(*calculate filling factor*)

(*--------------------------------------------------------------------------------*)
(*default for LHCb RICHes*)
(*--------------------------------------------------------------------------------*)
eff0GeoAccFactorInterPixel=1;(* !@#$% To Do *)
eff0GeoAccFactorInterEleCell=1 ;(* !@#$% To Do *)
eff0GeoAccFactorInterColumns=1 ;(* !@#$% To Do *)
eff0InSensorGeomAccInBBRaw=1;
eff0InSensorGeomAccInBB:=
eff0InSensorGeomAccInBBRaw*eff0GeoAccFactorInterPixel*eff0GeoAccFactorInterEleCell*eff0GeoAccFactorInterColumns;
(**)
effInSensorGeomAcc:=eff0InSensorGeomAccInBB;
effInAllTheOverallMarginFactor=1;
effInDAQ=1;
effInFrontEnd=0.9;
effInGasRadAbsorption=1;
effInLensesInterfaceReflectivity=1;
effInLensesAbsorption=1;
effInSensorCollectEff=0.9;
effInSensorInterfaceReflectivity=1;
effInSensorMultiplication=1;
effInMirror1IfNotWavLenDependentReflectivity=1(*0.92*);(* -->> averageMirrorReflectivityFunctionWavLen*)
effInMirror2IfNotWavLenDependentReflectivity=1(*0.92*);(* -->> averageMirrorReflectivityFunctionWavLen*)
effInQuartzPlateAbsorption=1;
effInQuartzPlateInterfaceReflectivity=0.98*0.98;
effInReco=1;
effInAna=1;
(**)
myNotebookInit`bigBanner["\< default efficiency data \>"];
(**)
(*miniBanner["\< Summary of all efficiencies used only internally \>"];*)
(*miniBanner["\< ---***--- Summary of all efficiencies ---***--- \>"];*)
efficiencyDebugPrintout;
(**)
myNotebookInit`bigBanner["\<starting specific data for sensor: \>"<>sensor];
(*--------------------------------------------------------------------------------*)
If[(sensor=="\<TB2021A\>"),
(*--------------------------------------------------------------------------------*)
effInMirror1IfNotWavLenDependentReflectivity=1;
effInMirror2IfNotWavLenDependentReflectivity=1;
effInQuartzPlateInterfaceReflectivity=1;
effInQuartzPlateAbsorption=1;
effInSensorCollectEff=0.9;
effInAllTheOverallMarginFactor=1
];
(**)
(*--------------------------------------------------------------------------------*)
If[((sensor=="\<LAPPDTM\>")),(*assume identical to MAPMT22 so far ... *)
(*--------------------------------------------------------------------------------*)
myNotebookInit`bigBanner["\<assume geometrical factors identical to MAPMT22 so far ... \>"];
(* guesses *)
eff0GeoAccFactorInterColumns=55.4/56.5;(*assume identical to MAPMT22 so far ... *)
eff0GeoAccFactorInterEleCell=55.4/56.0;(*assume identical to MAPMT22 so far ... *)
eff0InSensorGeomAccInBBRaw=(2.675*2.675*64*4)/(55.4)^(2);(*assume identical to MAPMT22 so far ... *)
Print["\<Overall geo. acc. cross-check HERE  = \>",eff0GeoAccFactorInterColumns*eff0GeoAccFactorInterEleCell*eff0InSensorGeomAccInBBRaw];(*assume identical to MAPMT22 so far ... *)
Print["\<Overall geo. acc. cross-check EXACT = \>",(6*4*4*64*((2.875-0.2))^(2))/(56.5*(56.0*24))];(*assume identical to MAPMT22 so far ... *)
effInSensorCollectEff=0.9;(*assume identical to MAPMT22 so far ... *)
effInAllTheOverallMarginFactor=0.8(* BY HAND COMPARING THE DREAM DETECTOR WITH MORE REASONABLE MEASUREMENTS BUT STILL OPTIMISTIC *)
];
(*--------------------------------------------------------------------------------*)
If[(sensor=="\<MAPMTOLD22\>")||(sensor=="\<MAPMT22\>")||(sensor=="\<MAPMT22s\>")||(sensor=="\<MAPMT22l\>"),
(*--------------------------------------------------------------------------------*)
(* BaseBoard size side: 55.4 mm *)
(* mapmt pitch: 28 mm *)
(* mapmt sensitive area side: 23 mm *)
(*effInSensorGeomAcc=(23/(27.2+0.5))^2 =0.6894*)(* OLD good approx *)
(*eff0GeoAccFactorInterPixel=1;*)(* !@#$% To Do *)
(* RICH1
The Elementary Cell includes 2x2 photon detectors with a pitch of 28 mm.
The Elementary Cells are assembled on a column.
A column is composed of 22 Elementary Cells with pitches of 56 mm.
The column are assembled with a pitch of 56.5 mm.
Each photon detector assembly is made of 11 columns.
*)
eff0GeoAccFactorInterColumns=55.4/56.5;(* the interplay of these two is conservative.... gaps crossings are counted twice... *)
eff0GeoAccFactorInterEleCell=55.4/56.0;(* the interplay of these two is conservative.... gaps crossings are counted twice... *)
If[(sensor=="\<MAPMTOLD22\>")||(sensor=="\<MAPMT22\>")||(sensor=="\<MAPMT22s\>"),
miniBanner["\< small MAPMT\>"];
eff0InSensorGeomAccInBBRaw=(2.675*2.675*64*4)/(55.4)^(2);
Print["\<Overall geo. acc. cross-check HERE  = \>",eff0GeoAccFactorInterColumns*eff0GeoAccFactorInterEleCell*eff0InSensorGeomAccInBBRaw];
Print["\<Overall geo. acc. cross-check EXACT = \>",(6*4*4*64*((2.875-0.2))^(2))/(56.5*(56.0*24))];
];
If[(sensor=="\<MAPMT22l\>"),
miniBanner["\< large MAPMT\>"];
eff0InSensorGeomAccInBBRaw=(6*6*64)/(55.4)^(2);
Print["\<Overall geo. acc. cross-check HERE  = \>",eff0GeoAccFactorInterColumns*eff0GeoAccFactorInterEleCell*eff0InSensorGeomAccInBBRaw];
Print["\<Overall geo. acc. cross-check EXACT = \>",(4*64*((6-0.2))^(2))/(56.5*(56.0))];
];
effInSensorCollectEff=0.9;(*MUST ADD TO THIERRY DATA*)
effInAllTheOverallMarginFactor=1;
];
(*--------------------------------------------------------------------------------*)
If[((sensor=="\<SIPMFBK\>")||sensor=="\<MPPCHPK\>"),(*assume identical so far....*)
(*--------------------------------------------------------------------------------*)
(* guesses *)
(*FROM HAMAMATSU Datasheet S13361-2050ne-08 series((64*2*2)/(17.8)^(2))((17.8/(17.8+0.5)))^(2)=0.7644 // same gaps will be 1mm not 0.5mm, not all; this is single module *)
eff0InSensorGeomAccInBBRaw=0.76;(* SHORTCUT : ok, but this is the grand-total inDev*inPDA // value for 2mm pixels *)
effInSensorCollectEff=1;(* !@#$% To Do *)
effInSensorInterfaceReflectivity=1;(* !@#$% To Do *)
effInSensorMultiplication=1;(* !@#$% To Do *)
effInAllTheOverallMarginFactor=1
];
(**)
(* 250<\[Lambda]<550 effInMirrorAverageReflectivity 0.90<...<0.96 *)
(* 200<\[Lambda]<250 effInMirrorAverageReflectivity 0.50<...<0.90 *)
(* 550<\[Lambda] ignora effInMirrorAverageReflectivity 0.70<...<0.90 *)
totEff:=
effInGasRadAbsorption*
effInMirror1IfNotWavLenDependentReflectivity*(*main mirror*)
effInMirror2IfNotWavLenDependentReflectivity*(*secondary mirror*)
effInQuartzPlateInterfaceReflectivity*
effInQuartzPlateAbsorption*
effInLensesInterfaceReflectivity*
effInLensesAbsorption*
effInSensorGeomAcc*
effInSensorCollectEff*
effInSensorInterfaceReflectivity*
effInSensorMultiplication*
effInFrontEnd*
effInReco*
effInDAQ*
effInAna*
effInAllTheOverallMarginFactor;
(**)
myNotebookInit`bigBanner["\< specific efficency data used in the present run \>"];
(**)
(*miniBanner["\< Summary of all efficiencies used only internally \>"];*)
(*miniBanner["\< ---***--- Summary of all efficiencies ---***--- \>"];*)
efficiencyDebugPrintout;
(**)
thisTotEff=Round[totEff,epsRaw];
printTempD@thisTotEff;
(**)
Print["\< All constant loss factors ---  Product of constant efficiency factors: totEff : \>",nfpm2@totEff];
(**)
thisFormat[x_]:=If[Rationalize[x]!=1, PaddedForm[x,{7,2}],1];
Print[tmpRes=TableForm@Transpose[{
Flatten@Join[{eff0Names,effNames}],
Flatten@Join[{Round[allEff0,epsRaw],Round[allEff,epsRaw]}]}]
(*Flatten@Join[{thisFormat/@allEff0,thisFormat/@allEff}]}]*)
];
Export["\<C:\\TEMP\\allEff-\>"<>fileNameTag<>"\<.txt\>",tmpRes,"\<Table\>"];
(*--------------------------------------------------------------------------------*)
(*--------------------------------------------------------------------------------*)
(*HERE:everything causing photon losses in a energy dependent way*)
(*--------------------------------------------------------------------------------*)
(*--------------------------------------------------------------------------------*)
If[sensor=="\<UV\>",pdeEffEnergyData=MaPMTSBAUVGlassEffEnergyData;miniBanner["\< UV sensor \>"]];
If[sensor=="\<BS\>",pdeEffEnergyData=MaPMTSBABSGlassEffEnergyData;miniBanner["\< BS sensor \>"]];
If[sensor=="\<UVSE\>",pdeEffEnergyData=MaPMTSBAUVGlassEffEnergyDataSE;miniBanner["\< UV/SE sensor \>"]];
If[sensor=="\<BSSE\>",pdeEffEnergyData=MaPMTSBABSGlassEffEnergyDataSE;miniBanner["\< BS/SE sensor \>"]];
If[sensor=="\<MAPMTOLD22\>",pdeEffEnergyData=MAPMTOLD22EnergyData;miniBanner["\< MAPMTOLD22 \>"]];
If[sensor=="\<LAPPDTM\>",pdeEffEnergyData=LAPPDTMEnergyData;miniBanner["\< LAPPDTM \>"]];
If[sensor=="\<MAPMT22\>",pdeEffEnergyData=MAPMT22EnergyData;miniBanner["\< MAPMT22 \>"]];
If[sensor=="\<MAPMT22s\>",pdeEffEnergyData=MAPMT22EnergyData;miniBanner["\< MAPMT22s \>"]];
If[sensor=="\<MAPMT22l\>",pdeEffEnergyData=MAPMT22EnergyData;miniBanner["\< MAPMT22l \>"]];
If[sensor=="\<SIPMFBK\>",pdeEffEnergyData=SIPMFBKEnergyData;miniBanner["\< SIPMFBK \>"]];
If[sensor=="\<MPPCHPK\>",pdeEffEnergyData=MPPCHPKEnergyData;miniBanner["\< MPPCHPK \>"]];
If[sensor=="\<TB2021A\>",pdeEffEnergyData=TB2021AEnergyData;miniBanner["\< TB2021A - preliminary \>"]];
If[sensor=="\<ZERO\>",thisTotEff=1;pdeEffEnergyData=Table[{k,thisTotEff},{k,minEne,maxEne,epsRaw}];miniBanner["\< Perfect Detector \>"]];
(**)
Print["\< sensor is: \>",sensor];
(**)
pdeEffWavLenData=Transpose[{\[Lambda][Transpose[pdeEffEnergyData][[1]]],Transpose[pdeEffEnergyData][[2]]}];
(**)
printD[\[Lambda][minEne]];
printD[\[Lambda][maxEne]];
(**)
Print["\<this TotEff : \>",nf3@thisTotEff];
(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\<(* pdeEffEnergyData versus ENERGY *)\>"];
(*--------------------------------------------------------------------------------*)
tablePdeEffEnergyData=
Map[{NumberForm[#[[1]],{7,2}],NumberForm[#[[2]],{7,3}]}&,Reverse[1.0*pdeEffEnergyData]];
debugPrint@TableForm@tablePdeEffEnergyData;
plotPdeEffEnergyData=debugPrint@ListPlot[pdeEffEnergyData,
PlotLabel->StringJoin[title,"\<Efficiency versus Energy - data \>"],
GridLines->Automatic,
AxesLabel->labelEffVsEv,
PlotRange->{{minEne0,maxEne0},{0,1}}];
(**)
pdeEffEnergyFunction=SetPrecision[Interpolation[pdeEffEnergyData],wp];
plotPdeEffEnergyFunction=Plot[window[z,minEne,maxEne]*pdeEffEnergyFunction[z],{z,minEne0,maxEne0},
Epilog->{Map[Point,pdeEffEnergyData]},
PlotLabel->StringJoin[title,"\<Efficiency versus Energy - function \>"],
GridLines->Automatic,
AxesLabel->labelEffVsEv,
PlotRange->{{minEne0,maxEne0},{0,1}}];
Export["\<C:\\TEMP\\totEff-versus-ene-spectrum-table-\>"<>fileNameTag<>"\<.txt\>",tablePdeEffEnergyData,"\<TABLE\>"];
Export["\<C:\\TEMP\\totEff-versus-ene-spectrum-plot-\>"<>fileNameTag<>"\<.pdf\>",plotPdeEffEnergyFunction,"\<PDF\>"];
Print@plotPdeEffEnergyFunction;
(**)
(*--------------------------------------------------------------------------------*)
miniBanner["\<(* pdeEffWavLenData versus WAVLEN *)\>"];
(*--------------------------------------------------------------------------------*)
tablePdeEffWavLenData=
Map[{NumberForm[#[[1]],{7,1}],NumberForm[#[[2]],{7,3}]}&,1.0*pdeEffWavLenData];
debugPrint@TableForm@tablePdeEffWavLenData;
plotPdeEffWavLenData=debugPrint@ListPlot[pdeEffWavLenData,
PlotLabel->StringJoin[title,"\<Efficiency versus WavLen - data \>"],
GridLines->Automatic,
AxesLabel->labelEffVsNm,
PlotRange->{{minLam0,maxLam0},{0,1}}];
(**)
pdeEffWavLenFunction=SetPrecision[Interpolation[pdeEffWavLenData],wp];
plotPdeEffWavLenFunction=Plot[window[z,minLam,maxLam]*pdeEffWavLenFunction[z],{z,minLam0,maxLam0},
Epilog->{Map[Point,pdeEffWavLenData]},
PlotLabel->StringJoin[title,"\<Efficiency versus WavLen - function \>"],
GridLines->Automatic,
AxesLabel->labelEffVsNm,
PlotRange->{0,1}];
Export["\<C:\\TEMP\\totEff-versus-lam-spectrum-table-\>"<>fileNameTag<>"\<.txt\>",tablePdeEffWavLenData,"\<TABLE\>"];
Export["\<C:\\TEMP\\totEff-versus-lam-spectrum-plot-\>"<>fileNameTag<>"\<.pdf\>",plotPdeEffWavLenFunction,"\<PDF\>"];
debugPrint@plotPdeEffWavLenFunction;
(**)
(*--------------------------------------------------------------------------------*)
(* yield, for saturated rings *)
(* ENERGY *)
(*--------------------------------------------------------------------------------*)
debugPrint[miniBanner["\< Energy // BELOW: SPECTRUM FOR HIGH-MOMENTUM TRACKS ONLY !!! beta=1 \>"]];
sinSquaredThetaSatEnergy[sE_]:=Max[0,(1-1/((refrIndex[\[Lambda][sE]]))^(2))];
(*energy dependent factors*)
gE[sE_?NumericQ]:=SetPrecision[Max[0,pdeEffEnergyFunction[sE]*((averageMirrorReflectivityFunctionEnergy[sE]))^(2)],wp];
(* Total yield per meter *)
fE[sE_?NumericQ]:=SetPrecision[window[sE,minEne,maxEne]*theChrYieldConstant*thisTotEff*sinSquaredThetaSatEnergy[sE]*gE[sE],wp];
(*--------------------------------------------------------------------------------*)
miniBanner["\< fE - FULL energy spectrum \>"];
(*--------------------------------------------------------------------------------*)
localHisto=Plot[fE[sE],{sE,minEne0,maxEne0},PlotRange->{0,All},PlotLabel->"\< fE - FULL energy spectrum \>",AxesLabel->{"\<\[Epsilon] (eV)\>"},Ticks->{Automatic,None}];
debugPrint[localHisto];
Export["\<C:\\TEMP\\yield-fE-full-energy-spectrum-\>"<>fileNameTag<>"\<.pdf\>",localHisto,"\<PDF\>"];
Clear[localHisto];
plotSinSquaredThetaSatEnergy=Plot[
window[sE,minEne,maxEne]*sinSquaredThetaSatEnergy[sE],{sE,minEne0,maxEne0},
GridLines->Automatic,PlotLabel->StringJoin[title,"\<sinSquaredThetaSatEnergy\>"],AxesLabel->{"\<\[Epsilon] (eV)\>"}];
debugPrint[plotSinSquaredThetaSatEnergy];
(**)
(*--------------------------------------------------------------------------------*)
(* yield, for saturated rings*)
(* WAVLEN *)
(*--------------------------------------------------------------------------------*)
debugPrint[miniBanner["\< WavLen // BELOW: SPECTRUM FOR HIGH-MOMENTUM TRACKS ONLY !!! beta=1 \>"]];
sinSquaredThetaSatWavLen[sL_]:=Max[0,(1-1/((refrIndex[sL]))^(2))];
(*energy dependent factors*)
gL[sL_?NumericQ]:=SetPrecision[Max[0,pdeEffWavLenFunction[sL]*((averageMirrorReflectivityFunctionWavLen[sL]))^(2)],wp];
(* Total yield per meter *)
(* MULTIPLY BY theConstantWavLenFromToEnergy AND DIVIDE BY WavLen SQUARE *)fL[sL_?NumericQ]:=SetPrecision[window[sL,minLam,maxLam]*theConstantWavLenFromToEnergy*theChrYieldConstant*thisTotEff*sinSquaredThetaSatWavLen[sL]*gL[sL]/(sL)^(2),wp];
(*--------------------------------------------------------------------------------*)
miniBanner["\< fL - FULL waveln spectrum \>"];
(*--------------------------------------------------------------------------------*)
localHisto=Plot[fL[sL],{sL,minLam0,maxLam0},PlotRange->{0,All},PlotLabel->"\< fL - FULL waveln spectrum \>",AxesLabel->{"\<\[Lambda] (nm)\>"},Ticks->{Automatic,None}];
debugPrint[localHisto];
Export["\<C:\\TEMP\\yield-fL-full-waveln-spectrum-\>"<>fileNameTag<>"\<.pdf\>",localHisto,"\<PDF\>"];
Clear[localHisto];
plotSinSquaredThetaSatWavLen=Plot[
window[sL,minLam,maxLam]*sinSquaredThetaSatWavLen[sL],{sL,minLam0,maxLam0},
GridLines->Automatic,PlotLabel->StringJoin[title,"\<sinSquaredThetaSatWavLen\>"],AxesLabel->{"\<\[Lambda] (nm)\>"}];
debugPrint[plotSinSquaredThetaSatWavLen];
(**)
(*--------------------------------------------------------------------------------*)
(* PLOTS *)
(*--------------------------------------------------------------------------------*)
plotTotYieldEnergy=Plot[fE[sE],{sE,minEne0,maxEne0},PlotRange->{0,All},GridLines->Automatic,PlotLabel->StringJoin[title,"\<Total Yield per Meter per eV\>"],AxesLabel->{"\<\[Epsilon] (eV)\>","\<d(yield)/d(\[Epsilon])\>"}(*,Ticks->{Automatic,None}*)];
debugPrint[plotTotYieldEnergy];
Export["\<C:\\TEMP\\plot-Tot-Yield-Energy-\>"<>fileNameTag<>"\<.pdf\>",plotTotYieldEnergy,"\<PDF\>"];
(**)
plotTotYieldWavLen=Plot[fL[sL],{sL,minLam0,maxLam0},PlotRange->{0,All},GridLines->Automatic,PlotLabel->StringJoin[title,"\<Total yield per Meter per nm\>"],AxesLabel->{"\<\[Lambda] (nm)\>","\<d(yield)/d(\[Lambda])\>"}(*,Ticks->{Automatic,None}*)];
debugPrint[plotTotYieldWavLen];
Export["\<C:\\TEMP\\plot-Tot-Yield-WavLen-\>"<>fileNameTag<>"\<.pdf\>",plotTotYieldWavLen,"\<PDF\>"];
(**)
plotThetaCWavLen=Plot[window[sL,minLam,maxLam]*1000*ArcCos[1/refrIndex[sL]],{sL,minLam0,maxLam0},PlotRange->{0,All},
GridLines->Automatic,PlotLabel->StringJoin[title,"\< \!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\) (mrad) \>"],AxesLabel->{"\<\[Lambda] (nm)\>","\< \!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\) (mrad) \>"}];
debugPrint[plotThetaCWavLen];
(**)
plotThetaCEnergy=Plot[window[sE,minEne,maxEne]*1000*ArcCos[1/refrIndex[\[Lambda][sE]]],{sE,minEne0,maxEne0},PlotRange->{0,All},
GridLines->Automatic,PlotLabel->StringJoin[title,"\< \!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\) (mrad) \>"],AxesLabel->{"\<\[Epsilon] (eV)\>","\< \!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\) (mrad) \>"}];
debugPrint[plotThetaCEnergy];
(**)
(*--------------------------------------------------------------------------------*)
(* INTEGRATED YIELD *)
(*--------------------------------------------------------------------------------*)
(*Start integration from large lamba and go down....stop at exact maxEne*)(*Be careful with quantization steps and matching limits and redefine deltaEneNIntegration*)
numBins=Round[(maxEne-minEne)/deltaEne]+10;
printD[numBins];
deltaEneNIntegration=(maxEne-minEne)/numBins;
deltaLamNIntegration=(maxLam-minLam)/numBins;
(*printD[minEne];printD[maxEne];printD[deltaEne];printD[numBins];printD@deltaEneNIntegration;*)
(**)
overallIntegratedPDEEne=NIntegrate[gE[sE],{sE,minEne,maxEne},WorkingPrecision->wp,AccuracyGoal->7];
Print["\< overall integrated PhDetEff (PDE*eV) - detector-only dependent \>",nf@overallIntegratedPDEEne];
overallIntegratedPDELam=NIntegrate[gL[sL],{sL,minLam,maxLam},WorkingPrecision->wp,AccuracyGoal->7];
Print["\< overall integrated PhDetEff (PDE*nm) - detector-only dependent \>",nf@overallIntegratedPDELam];
(**)
Print["\< # photons per meter all effects included (via ene calculation) \>",nf@NIntegrate[fE[sE],{sE,minEne,maxEne},WorkingPrecision->wp,AccuracyGoal->7]];
Print["\< # photons per meter all effects included (via lam calculation) \>",nf@NIntegrate[fL[sL],{sL,minLam,maxLam},WorkingPrecision->wp,AccuracyGoal->7]];
(**)
(*--------------------------------------------------------------------------------*)
myNotebookInit`bigBanner["\< integral yield function \!\(\*StyleBox["per",Background->RGBColor[1, 1, 0]]\)\!\(\*StyleBox[" ",Background->RGBColor[1, 1, 0]]\)\!\(\*StyleBox["meter",Background->RGBColor[1, 1, 0]]\) all effects included (via ene calculation) \>"];
(*--------------------------------------------------------------------------------*)
(* USE TABLE AND THE INTERPOLATE, AS I DID NOT MANAGE WITH FUNCTION DEFINED BY NINTEGRATE... *)
Print["\< slow calc... be patient... \>"];
integratedYieldEne=EchoTiming@Table[{s,
NIntegrate[fE[sE],{sE,minEne,s},MaxRecursion->200,WorkingPrecision->wp,AccuracyGoal->7]
},
{s,minEne,maxEne,deltaEneNIntegration}];
debugPrint["\< === Total integrated yield (via ene calculation) {s (eV), \!\(\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(s\)]\)\[Placeholder]\[DifferentialD]\[Placeholder]}  \>",nfPad[TableForm[1.0*integratedYieldEne],10,3,13]];
interpolatedIntegratedYieldEne=SetPrecision[Interpolation[integratedYieldEne],wp];
debugPrint["\< interpolatedIntegratedYieldEne :         \>",interpolatedIntegratedYieldEne];
(*full yield per meter*)
theIntegratedFullYieldEne=Last[integratedYieldEne][[2]];
debugPrint["\< theIntegratedFullYieldEne :                 \>",theIntegratedFullYieldEne];
plotInterpolatedIntegratedYieldEne=Plot[interpolatedIntegratedYieldEne[sE],{sE,minEne,maxEne},PlotRange->{{minEne0,maxEne0},All}];
debugPrint["\< plotInterpolatedIntegratedYieldEne :          \>",plotInterpolatedIntegratedYieldEne];
(*normalized full yield per meter*)
normalizedInterpolatedIntegratedYieldEne[sE_]=interpolatedIntegratedYieldEne[sE]/theIntegratedFullYieldEne;
plotNormalizedInterpolatedIntegratedYieldEne=Plot[normalizedInterpolatedIntegratedYieldEne[sE],{sE,minEne,maxEne},PlotRange->{{minEne0,maxEne0},All}];
debugPrint["\< plotNormalizedInterpolatedIntegratedYieldEne : \>",plotNormalizedInterpolatedIntegratedYieldEne];
(* Here non length-related quantities only: just #/meter *)
Print["\< Total Number of Photons per Meter :         \>",interpolatedIntegratedYieldEne[maxEne]];
(**)
(*--------------------------------------------------------------------------------*)
myNotebookInit`bigBanner["\< integral yield function \!\(\*StyleBox["per",Background->RGBColor[1, 1, 0]]\)\!\(\*StyleBox[" ",Background->RGBColor[1, 1, 0]]\)\!\(\*StyleBox["meter",Background->RGBColor[1, 1, 0]]\) all effects included (via lam calculation) \>"];
(*--------------------------------------------------------------------------------*)
(* USE TABLE AND THE INTERPOLATE, AS I DID NOT MANAGE WITH FUNCTION DEFINED BY NINTEGRATE... *)
Print["\< slow calc... be patient... \>"];
integratedYieldLam=EchoTiming@Table[{s,
NIntegrate[fL[sL],{sL,minLam,s},MaxRecursion->200,WorkingPrecision->wp,AccuracyGoal->7]},
{s,minLam,maxLam,deltaLamNIntegration}];
debugPrint["\< === Total integrated yield (via lam calculation) {\[Lambda] (nm), \!\(\*SubsuperscriptBox[\(\[Integral]\), \(-\[Infinity]\), \(\[Lambda]\)]\)\[Placeholder]\[DifferentialD]\[Placeholder]}  \>",nfPad[TableForm[1.0*integratedYieldLam],10,3,13]];
interpolatedIntegratedYieldLam=SetPrecision[Interpolation[integratedYieldLam],wp];
debugPrint["\< interpolatedIntegratedYieldLam :         \>",interpolatedIntegratedYieldLam];
(*full yield per meter*)
theIntegratedFullYieldLam=Last[integratedYieldLam][[2]];
debugPrint["\< theIntegratedFullYieldLam :                 \>",theIntegratedFullYieldLam];
plotInterpolatedIntegratedYieldLam=Plot[interpolatedIntegratedYieldLam[sL],{sL,minLam,maxLam},PlotRange->{{minLam0,maxLam0},All}];
debugPrint["\< plotInterpolatedIntegratedYieldLam :          \>",plotInterpolatedIntegratedYieldLam];
(*normalized full yield per meter*)
normalizedInterpolatedIntegratedYieldLam[sL_]=interpolatedIntegratedYieldLam[sL]/theIntegratedFullYieldLam;
plotNormalizedInterpolatedIntegratedYieldLam=Plot[normalizedInterpolatedIntegratedYieldLam[sL],{sL,minLam,maxLam},PlotRange->{{minLam0,maxLam0},All}];
debugPrint["\< plotNormalizedInterpolatedIntegratedYieldLam : \>",plotNormalizedInterpolatedIntegratedYieldLam];
(* Here non length-related quantities only: just #/meter *)
Print["\< Total Number of Photons per Meter :         \>",interpolatedIntegratedYieldLam[maxLam]];
(**)
myNotebookInit`bigBanner["\<fully Weighted Mean/Median via both Ene and Lam\>"];
(**)
If[debugPrintEnabledFlag==True,
medianDetEnergy=Round[sE/.FindRoot[normalizedInterpolatedIntegratedYieldEne[sE]==1/2,{sE,(minEne+maxEne)/2,minEne,maxEne}],epsRaw];
printD@nf1@medianDetEnergy
];
(**)
medianDetWavLen=Round[sL/.FindRoot[normalizedInterpolatedIntegratedYieldLam[sL]==1/2,{sL,(minLam+maxLam)/2,minLam,maxLam}],epsRaw];
printD@nf1@medianDetWavLen;
(**)
printD[nf[refrIndex[medianDetWavLen],12,8]];
(**)
,{InterpolatingFunction::dmval,NIntegrate::slwcon}];
(*On[NIntegrate::ncvb];
On[NIntegrate::precw];*)

(*skip the eff0: in  the summary they jsut make confusion...*)
(*allTheEfficiencies[sensor]={StringTrim/@Join[effNames,eff0Names],Round[Symbol/@StringTrim/@Join[effNames,eff0Names],epsRaw]};*)
allTheEfficiencies[sensor]={
StringTrim@effNames,
Round[Symbol/@StringTrim/@effNames,epsRaw]
};
printD@TableForm@Transpose@allTheEfficiencies[sensor];
(**)
miniBanner["\< calcDetectedPhotons - END \>"];
(**)
Return[{theIntegratedFullYieldEne,thisTotEff,overallIntegratedPDEEne,allTheEfficiencies[sensor][[2]]}]
];

(* ---- initialization cell 55 | 49a78982-4652-0747-a479-f02c43049369 ---- *)
ClearAll[doCalcAllRadiatorsSummary];

doCalcAllRadiatorsSummary[results_,resultsHeader_:detectorResultsNames]:=Module[{colWidt,fmtDigits1,fmtDigits2,fmtDigits3,fmtDigits4,fmtDigits7},
(**)
(*debugPrintEnabledFlag=False;*)
If[Length@results==0,Return[Print["\<doCalcAllRadiatorsSummary: no data, Return[]\>"]]];
(**)
Print["\< number of experiments and number of results  : \>",Dimensions[results]];
Print["\< all results are printed: number of results ==>> lines of output = \>",Length@detectorResultsNames];
(**)
fmtDigits1={{01},{02},{03},{04},{05},{20},{21},{22},{23},{24},{25},{26},{27},{29},{30},{31},{32},{33},{34},{35},{36},{40},{43},{44},{46}};
fmtDigits2={{12},{13},{14},{37},{41}};
fmtDigits3={{28},{42},{47},{48},{49},{50},{51},{52},{53},{54},{55},{56},{57},{58},{59},{60},{61},{62},{63},{64},{65}};
fmtDigits4={{11},{15},{38},{39}};
fmtDigits7={{06},{07},{08},{09},{16},{17},{18},{19},{45}};
usedFmtDigts=Sort@Join[fmtDigits1,fmtDigits2,fmtDigits3,fmtDigits4,fmtDigits7];
(*
debugPrintD@detectorResultsNames;
debugPrintD@Length@detectorResultsNames;
debugPrintD@usedFmtDigts;
debugPrintD@Length@usedFmtDigts;
debugPrintD@Complement[detectorResultsNames,detectorResultsNames[[Flatten@usedFmtDigts]]];
*)
(**)
colWidt=10;
Print@TableForm[
MapAt[nf[#,colWidt,7,6]&,
MapAt[nf[#,colWidt,4,6]&,
MapAt[nf[#,colWidt,3,6]&,
MapAt[nf[#,colWidt,2,6]&,
MapAt[nf[#,colWidt,1,6]&,
(* Here: explicit number formatting for relevant results *)
(* Don't format radiator and sensor, are strings; length-2 formats *)
Transpose[Join[{resultsHeader},{Range[Length@resultsHeader]},results]]
(*detectorResultsExport*)
,fmtDigits1]
,fmtDigits2]
,fmtDigits3]
,fmtDigits4]
,fmtDigits7]
,TableAlignments->{Right}
]
];

(* ---- initialization cell 56 | 6ed764c2-0114-7345-b3ee-ea0ed53e8ee7 ---- *)
(**************************************************************************************************)
(* DO calc OR just print *)
calcRadiatorDataFlag=False;
sensors={"\<LAPPDTM\>","\<MAPMT22\>","\<MPPCHPK\>","\<SIPMFBK\>"};
numSim=1000;
(**)
(**************************************************************************************************)
(* just debugging when calcRadiatorDataFlag=False *)
If[calcRadiatorDataFlag==False,
myNotebookInit`bigBanner["\<calcRadiatorDataFlag==False - DO NOTHING\>"]
];
(**)
(**************************************************************************************************)
(**)
doCalcRadiatorData:=Module[{detectorResultsC4F10,detectorResultsC1F04,detectorResultsC1O02,detectorResultsFQrtz,detectorResultsAERGL,(*detectorResultsExport,*)(*allDetectorResultsExport,*)tag,refrIndex,thisSensor,lengthDataRecord,(*detectorResultsExport,*)allRefrIndexAtWavLenMean,idx},
allDetectorResultsExport={};
Do[
myNotebookInit`bigBanner["\< new sensor \>"];
thisSensor=sensors[[idSensor]];
tag=thisSensor;
Print["\< thisSensor = \>", thisSensor];
lengthDataRecord=Length[detectorResultsNames];
printTempD@lengthDataRecord;
If[calcRadiatorDataFlag==True
,
(*=============================================================================================================*)
(*DO CALCULATIONS*)
(*=============================================================================================================*)
(*JUST (UN)/COMMENT THE NEXT LINES TO CHOOSE THE RADIATORS // TO BE IMPROVED*)
(*=============================================================================================================*)
detectorResultsC4F10=ConstantArray["\<\>",lengthDataRecord];
detectorResultsC1F04=ConstantArray["\<\>",lengthDataRecord];
(*detectorResultsC1O02=ConstantArray["\<\>",lengthDataRecord];
detectorResultsFQrtz=ConstantArray["\<\>",lengthDataRecord];
detectorResultsAERGL=ConstantArray["\<\>",lengthDataRecord];*)
(**)
(* Also redefines THE calculated average refrIndex *)
myNotebookInit`bigBanner[detectorResultsC4F10=calcRICHYield["\<C4F10-980-293\>",\[Lambda]MinRef,\[Lambda]MaxRef,1,thisSensor,0,numSim,True]];
myNotebookInit`bigBanner[detectorResultsC1F04=calcRICHYield["\<C1F04-980-293\>",\[Lambda]MinRef,\[Lambda]MaxRef,2,thisSensor,0,numSim,True]];
(*myNotebookInit`bigBanner[detectorResultsC1O02=calcRICHYield["\<C1O02\>",\[Lambda]MinRef,\[Lambda]MaxRef,2,thisSensor,0,numSim,True]];
myNotebookInit`bigBanner[detectorResultsFQrtz=calcRICHYield["\<FQrtz\>",\[Lambda]MinRef,\[Lambda]MaxRef,0,"\<ZERO\>",0,numSim,True]];
myNotebookInit`bigBanner[detectorResultsAERGL=calcRICHYield["\<AERGL\>",\[Lambda]MinRef,\[Lambda]MaxRef,0,"\<ZERO\>",0,numSim,True]];*)
(**)
If[Length[detectorResultsC4F10]!=lengthDataRecord,detectorResultsC4F10=ConstantArray["\<\>",lengthDataRecord]];
If[Length[detectorResultsC1F04]!=lengthDataRecord,detectorResultsC1F04=ConstantArray["\<\>",lengthDataRecord]];
(*If[Length[detectorResultsC1O02]!=lengthDataRecord,detectorResultsC1O02=ConstantArray["\<\>",lengthDataRecord]];
If[Length[detectorResultsFQrtz]!=lengthDataRecord,detectorResultsFQrtz=ConstantArray["\<\>",lengthDataRecord]];
If[Length[detectorResultsAERGL]!=lengthDataRecord,detectorResultsAERGL=ConstantArray["\<\>",lengthDataRecord]];*)
(**)
printD@detectorResultsC4F10;
printD@detectorResultsC1F04;
(*printD@detectorResultsC1O02;
printD@detectorResultsFQrtz;
printD@detectorResultsAERGL;*)
(**)
detectorResultsExport=Transpose[{detectorResultsNames,detectorResultsC4F10,detectorResultsC1F04(*,detectorResultsC1O02,detectorResultsFQrtz,detectorResultsAERGL*)}];
AppendTo[allDetectorResultsExport,detectorResultsExport];
(* all radiator data here; only sensor changes *)(* DO NOT USE fileNameTag *)
Export["\<C:\\TEMP\\radiator-data-export-\>"<>ToString[thisSensor]<>"\<-PlainText\>"<>"\<.txt\>",detectorResultsExport,"\<Text\>"];
(* all radiator data here; only sensor changes *)(* DO NOT USE fileNameTag *)
doCalcAllRadiatorsSummary[Transpose@detectorResultsExport];
(**)
myNotebookInit`bigBanner["\< tabular print of all the gas data \>"];
Print[TableForm@Transpose[{detectorResultsNames,Map[nf[#,20,6]&,detectorResultsC4F10]}]];
Print[TableForm@Transpose[{detectorResultsNames,Map[nf[#,20,6]&,detectorResultsC1F04]}]];
(*Print[TableForm@Transpose[{detectorResultsNames,Map[nf[#,20,6]&,detectorResultsC1O02]}]];
Print[TableForm@Transpose[{detectorResultsNames,Map[nf[#,20,6]&,detectorResultsFQrtz]}]];
Print[TableForm@Transpose[{detectorResultsNames,Map[nf[#,20,6]&,detectorResultsAERGL]}]];*)
(**)
myNotebookInit`bigBanner["\< tabular/column print of all the gas data (another) \>"];
Print[TableForm@detectorResultsExport];
(**)
idx=Flatten@Position[detectorResultsNames,"\<refrIndex[wavLenMean]\>"];
allRefrIndexAtWavLenMean=Drop[Flatten@detectorResultsExport[[idx]],1];(*get rid of the first element, the name*)
printTempD@allRefrIndexAtWavLenMean;
(**)
Do[
refrIndex=allRefrIndexAtWavLenMean[[idRad]];
printTempD@refrIndex;
Print[Plot[Evaluate[Table[thetaC[betaPart[thePartMasses[[thisPart]],x],refrIndex],{thisPart,1,5}]],{x,1,99},PlotRange->{0,1.1*ArcCos[1/refrIndex]},AxesLabel->{"\< p (GeV/c) \>","\< \!\(\*SubscriptBox[\(\[Theta]\), \(C\)]\) \>"}]];
Print[Table[SetPrecision[momentumThr[thePartMasses[[thisPart]],refrIndex],numPrecision],{thisPart,1,5}]];
Print[nf[Table[SetPrecision[betaPart[thePartMasses[[thisPart]],momentumThr[thePartMasses[[thisPart]],refrIndex]],numPrecision],{thisPart,1,5}],7,7]];
(**)
,{idRad,1,Length[allRefrIndexAtWavLenMean]}
]
,
(* JUST PRINT *)
Print[TableForm@detectorResultsExport]
]
,{idSensor,1,Length[sensors]}
];
Return[allDetectorResultsExport]
];
(**)
If[calcRadiatorDataFlag==True,
allTheDetectorResultsExport=doCalcRadiatorData;
allTheDetectorResultsExportShow=Transpose@Prepend[Join[
Drop[Transpose[allTheDetectorResultsExport[[1]]],1],
Drop[Transpose[allTheDetectorResultsExport[[2]]],1],
{1000+Range[Dimensions[allTheDetectorResultsExport][[2]]]}
],
detectorResultsNames
];
Export["\<C:\\TEMP\\all-detector-data-export\>"<>"\<.tex\>",
allTheDetectorResultsExportShowPrint=
TableForm[
MapAt[nf[#,20,7,6]&,
MapAt[nf[#,20,4,6]&,
MapAt[nf[#,20,3,6]&,
MapAt[nf[#,20,2,6]&,
MapAt[nf[#,20,1,6]&,
(*Don't format radiator and sensor, are strings; length-2 formats *)
allTheDetectorResultsExportShow
,{{01},{02},{03},{04},{20},{21},{22},{23},{24},{25},{26},{27},{29},{30},{31},{32},{33},{34},{35},{36},{40}}]
,{{12},{13},{37},{41}}]
,{}]
,{{09},{11},{15},{38},{39}}]
,{{05},{06},{07},{08},{16},{17},{18},{19},{28}}]
,TableAlignments->{Right}]
,"\<TeX\>"
]
];

Print@allTheDetectorResultsExportShowPrint;

(* ---- initialization cell 57 | 49adaebd-636e-a64c-b37a-6893d3935494 ---- *)
(*calcRICHYield["\<C4F10\>",\[Lambda]MinRef,\[Lambda]MaxRef,1,"\<LAPPDTM\>"]
calcRICHYield["\<C4F10\>",\[Lambda]MinRef,\[Lambda]MaxRef,1,"\<MAPMT22\>"]
killStop*)

(* ---- initialization cell 58 | d1a147f7-a23e-4582-8662-c16294ad8ce0 ---- *)
(**************************************************************************************************)
(*
{X,Y,Z}:= optica coordinates;
{x,y,z}:= LHCb coordinates;
Z <- x // X <- y // Y <- z;
AxesLabel->{"\<z(mm) {X}\>","\<x(mm) {Y}\>","\<y(mm) {Z}\>"}
*)
(**************************************************************************************************)

(* TO FIX;
xSize=2000;
xBoxMin=-xSize;
xBoxMax=+xSize;
yBoxMin=-2000;
yBoxMax=+2000;
zBoxMin=ZBoxMin;
zBoxMax=ZBoxMax;
First@myBoundary;
PlotRange->{{zBoxMin,zBoxMax},{XBoxMin,XBoxMax},{ YBoxMin,YBoxMax}}
*)

SetOptions[{LogPlot,Plot,Graphics,ListPlot,Histogram},
AspectRatio->1/2,
Axes->True,
AxesLabel->{"\<\>","\<\>"},
AxesOrigin->Automatic,
AxesStyle->Thick,
Background->White,
GridLines->Automatic,
ImageSize->Large,
LabelStyle->Directive[Background->White,FontFamily->"\<Helvetica\>",Bold,16],
PlotRange->All,
Ticks->{Automatic,None}
];
SetOptions[{Plot,LogPlot},Filling->Axis];
(**)
Options[Plot]
Options[ListPlot]
Options[Graphics]
Options[Histogram]
(**)

(* ---- initialization cell 59 | 39151723-654b-e842-8193-3f1d0a32952d ---- *)
(**)
(*NotebookDelete[Cells[EvaluationNotebook[],CellStyle->{"\<Output\>"}]];*)
(**)
(*NotebookDelete[Cells[EvaluationNotebook[],GeneratedCell->True]];*)
(**)
(*FrontEndExecute[FrontEndToken["\<DeleteGeneratedCells\>"]]*)
(**)
myNotebookInit`bigBanner["\< FINISHING INITIALIZATION \>"]
(**)
(*FrontEndExecute[FrontEndToken[EvaluationNotebook[],"\<SelectAll\>"]];*)
(*FrontEndTokenExecute["\<SelectionCloseAllGroups\>"];*)
(*FrontEndTokenExecute["\<SelectionOpenAllGroups\>"]*)
(**)

(* ---- initialization cell 60 | 16b41567-6371-b342-b759-56693b89057c ---- *)
Cells[CellStyle->{"\<MSG\>","\<Message\>"}]

(*Cells[CellStyle->{"\<Print\>","\<Output\>"}]*)

(* ---- initialization cell 61 | e8d85d8c-e191-f54f-9361-c2d7e5d85bd9 ---- *)
checkNewCreatedSymbols[]

showContextInfo[]

(* ---- initialization cell 62 | 3bd7aec4-925f-1744-86f4-30950e9f7eb2 ---- *)
EndPackage[]
