(* ::Package:: *)

(* Regenerated from CellStyleDataRules.nb using NotebookImport without a text conversion. *)
(* Each source cell was imported under HoldComplete, serialized in context-preserving FullForm, and syntax-checked without evaluation. *)

(* ::Title:: *)
(* CELL RULES *)

(* ::Subtitle:: *)
(* init *)

(* ::Input::Initialization:: *)
(* ---- initialization cell 1, expression 1 ---- *)
CompoundExpression[CompoundExpression[SetDirectory[NotebookDirectory[]], Null], Null, CompoundExpression[Print["NotebookDirectory[] : ", Directory[]], Null]]

(* ::Input::Initialization:: *)
(* ---- initialization cell 2, expression 1 ---- *)
CompoundExpression[Null]

(* ::Input::Initialization:: *)
(* ---- initialization cell 3, expression 1 ---- *)
CompoundExpression[CompoundExpression[Print[" SETTING CELL STYLE DATA RULES - CellStyleDataRules "], Null]]

(* ::Input::Initialization:: *)
(* ---- initialization cell 4, expression 1 ---- *)
CompoundExpression[CompoundExpression[Print[" InputNotebook                           ", InputNotebook[]], Null], Null, CompoundExpression[Print[" EvaluationNotebook                      ", EvaluationNotebook[]], Null], Null, CompoundExpression[Print[" This package lives at $InputFileName    ", $InputFileName], Null], Null, CompoundExpression[Print[" This package lives at $Input           ", $Input], Null]]

(* ::Subtitle:: *)
(* code *)

(* ::Input::Initialization:: *)
(* ---- initialization cell 5, expression 1 ---- *)
CompoundExpression[Null]

(* ::Input::Initialization:: *)
(* ---- initialization cell 6, expression 1 ---- *)
CompoundExpression[CompoundExpression[SetOptions[EvaluationNotebook[], Rule[AutoGeneratedPackage, Automatic], Rule[StyleDefinitions, Notebook[List[Cell[StyleData[Rule[StyleDefinitions, If[StringQ[Global`$RICHProjectStyleDefinitions], Global`$RICHProjectStyleDefinitions, "myStyle.nb"]]]], Cell[StyleData["Title"], Rule[CellGroupingRules, List["SectionGrouping", 0]], Rule[FontSize, 28]], Cell[StyleData["Subtitle"], Rule[CellGroupingRules, List["SectionGrouping", 10]], Rule[FontSize, 26]], Cell[StyleData["Subsubtitle"], Rule[CellGroupingRules, List["SectionGrouping", 20]], Rule[FontSize, 24]], Cell[StyleData["Chapter"], Rule[CellGroupingRules, List["SectionGrouping", 30]], Rule[FontSize, 22]], Cell[StyleData["Section"], Rule[CellGroupingRules, List["SectionGrouping", 40]], Rule[FontSize, 20]], Cell[StyleData["Subsection"], Rule[CellGroupingRules, List["SectionGrouping", 50]], Rule[FontSize, 18]], Cell[StyleData["Subsubsection"], Rule[CellGroupingRules, List["SectionGrouping", 60]], Rule[FontSize, 16]], Cell[StyleData["Code"], Rule[CellGroupingRules, List["SectionGrouping", 90]], Rule[FontSize, 14]], Cell[StyleData["Input"], Rule[CellGroupingRules, List["SectionGrouping", 90]], Rule[FontSize, 14]], Cell[StyleData["Text"], Rule[CellGroupingRules, List["SectionGrouping", 90]], Rule[FontSize, 12]], Cell[StyleData["Output"], Rule[CellGroupingRules, List["SectionGrouping", 90]], Rule[FontSize, 14]], Cell[StyleData["Message"], Rule[CellGroupingRules, List["SectionGrouping", 92]], Rule[FontSize, 12]], Cell[StyleData["ExampleText"], Rule[CellGroupingRules, List["SectionGrouping", 91]], Rule[FontSize, 12]]]]]], Null]]

(* ::Input::Initialization:: *)
(* ---- initialization cell 7, expression 1 ---- *)
CompoundExpression[Null]

(* ::Input::Initialization:: *)
(* ---- initialization cell 8, expression 1 ---- *)
CompoundExpression[Null]

(* ::Title:: *)
(* style examples *)

(* ::Subtitle:: *)
(* another1 *)

(* ::Section:: *)
(* test1 *)

(* ::Section:: *)
(* test2 *)

(* ::Subsubtitle:: *)
(* another2 *)

(* ::Subtitle:: *)
(* subTitle *)

(* ::Subsubtitle:: *)
(* subSubTitle1 *)

(* ::Subsubtitle:: *)
(* subSubTitle2 *)

(* ::Section:: *)
(* jjjj *)

(* ::Subtitle:: *)
(* jjjj *)

(* ::Subtitle:: *)
(* jjj *)

(* ::Section:: *)
(* pppppp *)

(* ::Subsubtitle:: *)
(* kkk *)

(* ::Subsubtitle:: *)
(* gggg *)

(* ::Subtitle:: *)
(* hhh *)

(* ::Subsubtitle:: *)
(* gggg *)

(* ::Section:: *)
(* SECTION *)

(* ::Section:: *)
(* ggg *)

(* ::Subsection:: *)
(* jjjjjjj *)

(* ::Subsubsection:: *)
(* ggggg *)

(* ::Subsubsection:: *)
(* gyugyugug *)

(* ::Subsection:: *)
(* hhhhhh
 *)

(* ::Section:: *)
(* hhhhh *)

(* ::Title:: *)
(* END *)

(* ::Input::Initialization:: *)
(* ---- initialization cell 9, expression 1 ---- *)
CompoundExpression[CompoundExpression[Print["  END  ", EvaluationNotebook[]], Null]]