(* ::Package:: *)

(* ::Text:: *)
(*This package/notebook defines Cells style; subjective preferences.... as such it is not really needed.*)


(* ::Title::Initialization::Closed:: *)
(*CELL RULES*)


(* ::Subtitle::Initialization::Closed:: *)
(*init*)


(* ::Text::Initialization:: *)
(*MyWork.nb ---- Get["MyPackage.m"] ----> MyPackage.m*)
(*(interactive)                           (package)*)
(**)
(*Query              | Inside MyWork.nb  | Inside MyPackage.m (during Get)*)
(*-------------------|-------------------|--------------------------------*)
(*InputNotebook[]    | MyWork.nb  [OK]   | MyWork.nb  [OK]  (focus is still there)*)
(*EvaluationNotebook[]| MyWork.nb  [OK]  | also MyWork.nb  [OK]*)
(**)
(*NOTE: during Get["MyPackage.m"], both return MyWork.nb, because the*)
(*evaluation was initiated from a cell in MyWork.nb. The package file*)
(*itself is not a notebook object -- it has no NotebookObject.*)


(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]] ;(* make sure you will pick myStyle.nb in the same directory as the calling notebook directory *)
Print["NotebookDirectory[] : ",Directory[]];


(* ::Input::Initialization:: *)
(**************************************************************************************************)
(* my personal stuff *)
(**************************************************************************************************)


(* ::Input::Initialization:: *)
Print[" SETTING CELL STYLE DATA RULES - CellStyleDataRules "];


(* ::Input::Initialization:: *)
Print[" InputNotebook                           ",InputNotebook[]];(* nb: it is the calling notebook *)
Print[" EvaluationNotebook                      ",EvaluationNotebook[]];(* if loaded by Get[], it is the calling notebook *)
Print[" This package lives at $InputFileName    ",$InputFileName];
Print[" This package lives at $Input           ",$Input];


(* ::Subtitle::Initialization::Closed:: *)
(*code*)


(* ::Input::Initialization:: *)
(*SetOptions[EvaluationNotebook[],CellGrouping->Manual];*)
(*SetOptions[EvaluationNotebook[],CellGrouping->Automatic];*)


(* ::Input::Initialization:: *)
SetOptions[EvaluationNotebook[],AutoGeneratedPackage->Automatic,StyleDefinitions->Notebook[{
Cell[StyleData[StyleDefinitions->"myStyle.nb"]],
Cell[StyleData["Title"],CellGroupingRules->{"SectionGrouping",00},FontSize->28],Cell[StyleData["Subtitle"],CellGroupingRules->{"SectionGrouping",10},FontSize->26],Cell[StyleData["Subsubtitle"],CellGroupingRules->{"SectionGrouping",20},FontSize->24],Cell[StyleData["Chapter"],CellGroupingRules->{"SectionGrouping",30},FontSize->22],Cell[StyleData["Section"],CellGroupingRules->{"SectionGrouping",40},FontSize->20],Cell[StyleData["Subsection"],CellGroupingRules->{"SectionGrouping",50},FontSize->18],Cell[StyleData["Subsubsection"],CellGroupingRules->{"SectionGrouping",60},FontSize->16],Cell[StyleData["Code"],CellGroupingRules->{"SectionGrouping",90},FontSize->14],Cell[StyleData["Input"],CellGroupingRules->{"SectionGrouping",90},FontSize->14],Cell[StyleData["Text"],CellGroupingRules->{"SectionGrouping",90},FontSize->12],Cell[StyleData["Output"],CellGroupingRules->{"SectionGrouping",90},FontSize->14],Cell[StyleData["Message"],CellGroupingRules->{"SectionGrouping",92},FontSize->12],Cell[StyleData["ExampleText"],CellGroupingRules->{"SectionGrouping",91},FontSize->12]}]
];


(* ::Input::Initialization:: *)
(* example: CHANGE "TITLE" TO "SECTION" *)
(*( SelectionMove[#, All, Cell];  FrontEndTokenExecute[EvaluationNotebook[], "Style", "Section"]) & /@ Cells[CellStyle -> "Title"]*)


(* ::Input::Initialization:: *)
(*changeStyle[cell_CellObject,style_String]:=NotebookWrite[cell,ReplacePart[NotebookRead[cell],2->style]];*)


(* ::Title::Closed:: *)
(*style examples*)


(* ::Subtitle::Initialization::Closed:: *)
(*another1*)


(* ::Section::Initialization:: *)
(*test1*)


(* ::Section::Initialization:: *)
(*test2*)


(* ::Subsubtitle::Initialization::Closed:: *)
(*another2*)


(* ::Text::Initialization:: *)
(*text*)


(* ::Subtitle::Initialization::Closed:: *)
(*subTitle*)


(* ::Subsubtitle::Initialization:: *)
(*subSubTitle1*)


(* ::Subsubtitle::Initialization::Closed:: *)
(*subSubTitle2*)


(* ::Section::Initialization:: *)
(*jjjj*)


(* ::Subtitle::Initialization:: *)
(*jjjj*)


(* ::Subtitle::Initialization::Closed:: *)
(*jjj*)


(* ::Section::Initialization:: *)
(*pppppp*)


(* ::Subsubtitle::Initialization:: *)
(*kkk*)


(* ::Subsubtitle::Initialization:: *)
(*gggg*)


(* ::Subtitle::Initialization::Closed:: *)
(*hhh*)


(* ::Subsubtitle::Initialization::Closed:: *)
(*gggg*)


(* ::Section::Initialization:: *)
(*SECTION*)


(* ::Section::Initialization::Closed:: *)
(*ggg*)


(* ::Subsection::Initialization::Closed:: *)
(*jjjjjjj*)


(* ::Subsubsection::Initialization:: *)
(*ggggg*)


(* ::Subsubsection::Initialization:: *)
(*gyugyugug*)


(* ::Subsection::Initialization:: *)
(*hhhhhh*)
(**)


(* ::Section::Initialization:: *)
(*hhhhh*)


(* ::Title::Initialization::Closed:: *)
(*END*)


(* ::Input::Initialization:: *)
Print["  END  ",EvaluationNotebook[]];
