(* Extracted from CellStyleDataRules.nb. Definitions preserve original initialization-cell order. *)
(* Generated mechanically; validate in a clean Wolfram kernel before deleting legacy-original/. *)

(* ---- initialization cell 1 | aa4b0509-dccf-484d-9780-e130ccd14db7 ---- *)
SetDirectory[NotebookDirectory[]] ;(* make sure you will pick myStyle.nb in the same directory as the calling notebook directory *)

Print["\<NotebookDirectory[] : \>",Directory[]];

(* ---- initialization cell 2 | 298aead6-937d-cc43-b9ea-724102504076 ---- *)
(**************************************************************************************************)
(* my personal stuff *)
(**************************************************************************************************)

(* ---- initialization cell 3 | 0ea7dd28-f795-4223-8f83-377a686cd509 ---- *)
Print["\< SETTING CELL STYLE DATA RULES - CellStyleDataRules \>"];

(* ---- initialization cell 4 | 93f47cbc-b10a-4fda-be50-0d61fb4423fe ---- *)
Print["\< InputNotebook                           \>",InputNotebook[]];(* nb: it is the calling notebook *)

Print["\< EvaluationNotebook                      \>",EvaluationNotebook[]];(* if loaded by Get[], it is the calling notebook *)

Print["\< This package lives at $InputFileName    \>",$InputFileName];

Print["\< This package lives at $Input           \>",$Input];

(* ---- initialization cell 5 | b5261667-9c06-7f4e-9ab8-00c95bfa7ed6 ---- *)
(*SetOptions[EvaluationNotebook[],CellGrouping->Manual];*)
(*SetOptions[EvaluationNotebook[],CellGrouping->Automatic];*)

(* ---- initialization cell 6 | 0f187dd2-81f8-4d4a-a233-3f935545e3f7 ---- *)
SetOptions[EvaluationNotebook[],AutoGeneratedPackage->Automatic,StyleDefinitions->Notebook[{
Cell[StyleData[StyleDefinitions->"\<myStyle.nb\>"]],
Cell[StyleData["\<Title\>"],CellGroupingRules->{"\<SectionGrouping\>",00},FontSize->28],Cell[StyleData["\<Subtitle\>"],CellGroupingRules->{"\<SectionGrouping\>",10},FontSize->26],Cell[StyleData["\<Subsubtitle\>"],CellGroupingRules->{"\<SectionGrouping\>",20},FontSize->24],Cell[StyleData["\<Chapter\>"],CellGroupingRules->{"\<SectionGrouping\>",30},FontSize->22],Cell[StyleData["\<Section\>"],CellGroupingRules->{"\<SectionGrouping\>",40},FontSize->20],Cell[StyleData["\<Subsection\>"],CellGroupingRules->{"\<SectionGrouping\>",50},FontSize->18],Cell[StyleData["\<Subsubsection\>"],CellGroupingRules->{"\<SectionGrouping\>",60},FontSize->16],Cell[StyleData["\<Code\>"],CellGroupingRules->{"\<SectionGrouping\>",90},FontSize->14],Cell[StyleData["\<Input\>"],CellGroupingRules->{"\<SectionGrouping\>",90},FontSize->14],Cell[StyleData["\<Text\>"],CellGroupingRules->{"\<SectionGrouping\>",90},FontSize->12],Cell[StyleData["\<Output\>"],CellGroupingRules->{"\<SectionGrouping\>",90},FontSize->14],Cell[StyleData["\<Message\>"],CellGroupingRules->{"\<SectionGrouping\>",92},FontSize->12],Cell[StyleData["\<ExampleText\>"],CellGroupingRules->{"\<SectionGrouping\>",91},FontSize->12]}]
];

(* ---- initialization cell 7 | 5854f3ea-4312-4e02-b599-62f51cb010bd ---- *)
(* example: CHANGE "\<TITLE\>" TO "\<SECTION\>" *)
(*( SelectionMove[#, All, Cell];  FrontEndTokenExecute[EvaluationNotebook[], "\<Style\>", "\<Section\>"]) & /@ Cells[CellStyle -> "\<Title\>"]*)

(* ---- initialization cell 8 | 524f639b-1163-4d06-a843-7951ba9ca3ef ---- *)
(*changeStyle[cell_CellObject,style_String]:=NotebookWrite[cell,ReplacePart[NotebookRead[cell],2->style]];*)

(* ---- initialization cell 9 | 70cd79c1-f4ad-40e4-a6ba-db8a7e28889d ---- *)
Print["\<  END  \>",EvaluationNotebook[]];
