(* ::Package:: *)

(* ::Text:: *)
(*This package/notebook defines general physics tools.*)


(* ::Subtitle:: *)
(*INIT*)


(* ::Input::Initialization:: *)
packageBanner["LOADING physicsGeneral"];
bigBanner["--->>> might need some specific symbols defined elsewhere!"];


(* ::Input::Initialization:: *)
(*If[$Notebooks,
Get["C:\\Users\\Ale\\My Drive\\allRICHWMMA\\myNotebookInit.wl"];
Get["C:\\Users\\Ale\\My Drive\\allRICHWMMA\\myStyle.m"];
Get["C:\\Users\\Ale\\My Drive\\allRICHWMMA\\myDockedCells.wl"]
];*)


(* ::Input::Initialization:: *)
If[$Notebooks,
(**)
(* HERE TO ALLOW CHANGE SPECIFIC OPTIONS BELOW *)
(**)
(*SetOptions[EvaluationNotebook[],StyleDefinitions->"myStyle.nb"];*)(*SetOptions[EvaluationNotebook[],StyleDefinitions\[Rule]"StandardReport.nb"]*)(*SetOptions[EvaluationNotebook[],StyleDefinitions\[Rule]"Default.nb"]*)
SetOptions[EvaluationNotebook[],StyleDefinitions->If[StringQ[Global`$RICHProjectStyleDefinitions],Global`$RICHProjectStyleDefinitions,FileNameJoin[{ParentDirectory[NotebookDirectory[]],"myStyle.nb"}]]];
(**)
SetOptions[EvaluationNotebook[],AutoGeneratedPackage->None];SetOptions[EvaluationNotebook[],AutoMultiplicationSymbol->True];SetOptions[EvaluationNotebook[],Background->LightGreen];SetOptions[EvaluationNotebook[],CellEpilog:>SelectionMove[EvaluationNotebook[],Next,Cell]];SetOptions[EvaluationNotebook[],CellProlog:>SelectionMove[EvaluationCell[],All,Cell]];
SetOptions[EvaluationNotebook[],InitializationCellEvaluation->False];
SetOptions[EvaluationNotebook[],InitializationCellWarning->False];
SetOptions[EvaluationNotebook[],Magnification->3/4];
(*maximum size for explicit output*)
SetOptions[EvaluationNotebook[],OutputSizeLimit->1000000];
SetOptions[EvaluationNotebook[],PrivateNotebookOptions->{"FileOutlineCache"->False,"SafeFileOpen"->"IgnoreCache"}];SetOptions[EvaluationNotebook[],ShowCellLabel->False];SetOptions[EvaluationNotebook[],WindowMargins->{{0,Automatic},{Automatic,0}}];
(*SetOptions[EvaluationNotebook[],WindowSize\[Rule]Full]*)
SetOptions[EvaluationNotebook[],WindowSize->{Scaled[3/4],Scaled[1.0]}];
SetOptions[EvaluationNotebook[],WindowTitle->StringJoin[" ------- ",myNotebookInit`safeNotebookBaseName[]]];
(**)
SetOptions[EvaluationNotebook[],"DynamicUpdating"->True];(* It looks ok, even if it does not affect the tick in the Evaluation Menu ??? *)
(**)
(*Once[*)
If[
  ! TrueQ[Global`$RICHProjectManagedLoad],
  myNotebookInit`loadMyFile[
    "cellStyleDataRules.wl",
    DirectoryName[$InputFileName]
  ]
]
(*,"Notebook"]*)
(**)
];


(* ::Input::Initialization:: *)




(* ::Input::Initialization:: *)
BeginPackage[
  "physicsGeneral`",
  {"myNotebookInit`", "base`"}
];

Begin["`Private`"];
versionTAG="v.08-08-2026";
End[];



(* ::Input::Initialization:: *)
Unprotect[bet,beta,betaCherenkovThreshold,betaInfinity,betaPart,betaParticleFromMassAndMomentum,betaPartThr,betThr,chrnkvAngle,deltaMassSquare,energy,epsilonQuantum,gam,gamma,gammaCherenkovThreshold,gammaPart,gammaParticleFromMassAndMomentum,gamThr,m1,m2,m3,m4,m5,mass,masses,momentum,momentumCherenkovThreshold,momentumFromMassAndBeta,momentumFromMassAndGamma,momentumPart,momentumThr,momThr,numPrecision,numRelPho,precisionify,tC,tCAllPart,theHighPrecision,thePartMasses,theParts,thetaC,thetaChr,thetaChrTheMax,thisNumRelChr,thisThetaChr,toMass,tpl];

ClearAll[bet,beta,betaCherenkovThreshold,betaInfinity,betaPart,betaParticleFromMassAndMomentum,betaPartThr,betThr,chrnkvAngle,deltaMassSquare,energy,epsilonQuantum,gam,gamma,gammaCherenkovThreshold,gammaPart,gammaParticleFromMassAndMomentum,gamThr,m1,m2,m3,m4,m5,mass,masses,momentum,momentumCherenkovThreshold,momentumFromMassAndBeta,momentumFromMassAndGamma,momentumPart,momentumThr,momThr,numPrecision,numRelPho,precisionify,tC,tCAllPart,theHighPrecision,thePartMasses,theParts,thetaC,thetaChr,thetaChrTheMax,thisNumRelChr,thisThetaChr,toMass,tpl];



(* ::Input::Initialization:: *)
(**)
(*numPrecision=31;*)
theHighPrecision=23;
numPrecision=theHighPrecision;
precisionify=(SetPrecision[#,theHighPrecision]&);
epsilonQuantum=1000*10^-theHighPrecision;



(* ::Subtitle::Initialization:: *)
(*(*(*MECHANICS*)*)*)


(* ::Input::Initialization:: *)
(****************************************************************************************************)
(*TO CLEANUP*)
(****************************************************************************************************)
(**)
energy[mass_,momentum_]:=Sqrt[(mass)^2+(momentum)^2];
momentum[mass_,energy_]:=Sqrt[(energy)^2-(mass)^2];
mass[energy_,momentum_]:=Sqrt[(energy)^2-(momentum)^2];
(**)
(*\[Gamma][\[Beta]_]=(1-\[Beta]^2)^(-1/2);*)(*AVOID SINGLE LETTER FUNCTIONS*)
(*\[Beta][\[Gamma]_]=Sqrt[1-1/\[Gamma]^2];*)(*AVOID SINGLE LETTER FUNCTIONS*)
gamma[\[Beta]_]:= SetPrecision[1/(\[Sqrt](1-\[Beta]^2)),numPrecision];
beta[\[Gamma]_]:=SetPrecision[(\[Sqrt](-1+\[Gamma]^2))/\[Gamma],numPrecision];
(* ALIAS *)
gam[\[Beta]_]:=FullSimplify[gamma[\[Beta]]];
bet[\[Gamma]_]:=FullSimplify[beta[\[Gamma]]];
(**)
betaParticleFromMassAndMomentum[m_,p_]:=p/(\[Sqrt](m^2+p^2));
gammaParticleFromMassAndMomentum[m_,p_]:=Sqrt[p^2+m^2]/m;
(**)
momentumFromMassAndBeta[m_,\[Beta]_]:=m*\[Beta]*gamma[\[Beta]];
momentumFromMassAndGamma[m_,\[Gamma]_]:=m*beta[\[Gamma]]*\[Gamma];
(**)
gammaPart[\[Beta]_]:=SetPrecision[(1-\[Beta]^2)^(-1/2),numPrecision];
betaPart[m_,p_]:=SetPrecision[p/(\[Sqrt](m^2+p^2)),numPrecision];
momentumPart[m_,\[Beta]_]:=SetPrecision[m*\[Beta]*gammaPart[\[Beta]],numPrecision];
(**)
betaInfinity=Round[betaPart[1,1000],epsilonQuantum];
(* CHECK *)
Print[beta==FullSimplify[beta[gamma[beta]],0<beta<1]];
Print[gamma==FullSimplify[gamma[beta[gamma]],gamma>0]];
Print@betaParticleFromMassAndMomentum[m,p];
Print[N@betaInfinity];
Print[Precision[betaInfinity]];
(**)


(* ::Subtitle:: *)
(*RICH*)


(* ::Input::Initialization:: *)
(*to cleanup*)
(*thetaC[\[Beta]_,n_]:=SetPrecision[Re[ArcCos[1/(n*\[Beta])]],numPrecision];
thetaChr[\[Beta]_,n_]:=If[(n>=1)&&(0<=\[Beta]<=1)&&((n*\[Beta])>1),ArcCos[1/(n*\[Beta])],0];
*)


Unprotect[thetaCherenkov,thetaC,thetaChr];
ClearAll[thetaCherenkov,thetaC,thetaChr];
SetAttributes[{thetaCherenkov,thetaC,thetaChr},Listable];

(*NEW GENERAL*)
thetaCherenkov[\[Beta]_?NumericQ,n_?NumericQ,prec_:numPrecision]:=Which[n<1,0,\[Beta]<0||\[Beta]>1,0,n*\[Beta]<=1,0,True,SetPrecision[ArcCos[1/(n*\[Beta])],prec]];
thetaCherenkov[\[Beta]_,n_,prec_:numPrecision]:=ConditionalExpression[ArcCos[1/(n*\[Beta])],n>=1&&0<=\[Beta]<=1&&n*\[Beta]>1];

(*OLD ALIASES - TO CLEANUP*)
thetaC[\[Beta]_,n_]:=thetaCherenkov[\[Beta],n];
thetaChr[\[Beta]_,n_]:=thetaCherenkov[\[Beta],n];



chrnkvAngle[m_,p_,\[Lambda]_]:=Module[{physicsGeneral`Private`z},
physicsGeneral`Private`z=1/(betaPart[m,p]*theRefrIndex[\[Lambda]]); (* It has to be positive *)
physicsGeneral`Private`z=Map[Min[#,+1]&,physicsGeneral`Private`z]; (* z is non negative *)
Return[Chop[ArcCos[physicsGeneral`Private`z]]]
];
chrnkvAngleGeneral[m_,p_,\[Epsilon]_]:=ArcCot[D[\[Epsilon]*Tan[ArcCos[1/(betaPart[m,p]*theRefrIndex[\[Lambda][\[Epsilon]]])]],\[Epsilon]]];



(* ::Input::Initialization:: *)
(****************************************************************************************************)
(*TO CLEANUP*)
(****************************************************************************************************)
betaCherenkovThreshold[n_]:=1/n;
gammaCherenkovThreshold[n_]:=gamma[betaCherenkovThreshold[n]];
momentumCherenkovThreshold[m_,n_]:=FullSimplify[Rationalize[momentumFromMassAndBeta[m,betaCherenkovThreshold[n]]],n>0&&m>0];

betaPartThr[n_]:=SetPrecision[betaCherenkovThreshold[n],numPrecision];
momentumThr[m_,n_]:=SetPrecision[momentumCherenkovThreshold[m,n],numPrecision];
(* ALIAS *)
betThr[n_]:=betaCherenkovThreshold[n];
gamThr[n_]:=gammaCherenkovThreshold[n];
momThr[m_,n_]:=momentumCherenkovThreshold[m,n];
(* general *)

thetaChrTheMax[n_]:=thetaChr[1,n];
numRelPho[\[Beta]_,n_]:=If[(n>=1)&&(0<=\[Beta]<=1)&&((n*\[Beta])>1),Evaluate@FullSimplify[Sin[thetaChr[\[Beta],n]]^2/Sin[thetaChrTheMax[n]]^2],0];
(* this... = n pre-fixed; function of gamma; now it becomes mrad; add unit of measure *)
thisThetaChr[\[Gamma]_,n_:thisRefrIndex]:=Quantity[1000*thetaChr[beta[\[Gamma]],n],"Milliradians"];
thisNumRelChr[\[Gamma]_,n_:thisRefrIndex]:=numRelPho[beta[\[Gamma]],n];
(**)


(* ::Input::Initialization:: *)
(**************************************************************************************************)
(* General/generalized cherenkov angle formula *)
(**************************************************************************************************)
(*theRefrIndex[x_]:=1/(1+x/1000000000)*)
(*
k=n omega/c = 2Pi/lambda
lambda=2 Pi c/ n / omega 
 omega =2 Pi c/ n/lambda
theRefrIndex[\[Lambda]]=theRefrIndex[\[Lambda]]
D[n[\[Omega]],\[Omega]]=D[n[\[Omega]],\[Lambda]]*D[\[Lambda],\[Omega]]
*)
(*
g[m_,p_,\[Omega]_]:=
Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1]-(1/Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1])*\[Omega]*theRefrIndex[\[Lambda]0]*(betaPart[m,p])^2*D[n[\[Omega]],\[Omega]];
g[m,p,\[Omega]]
Print[Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1]-(1/Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1])\[Omega]0*theRefrIndex[\[Lambda]0]];

Print@Plot[chrnkvAngleGeneral[0.140,150,s]-Pi/2,{s,3,4}];
Print@Plot[chrnkvAngle[0.140,150,\[Lambda][s]],{s,3,4}];
*)


(* ::Input::Initialization:: *)
(*--------------------------------------------------------------------------------*)
(*thePartMasses={0.0005,0.106,0.140,0.494,0.936}; (* GeV/c^2 *)*)
thePartMasses={
QuantityMagnitude[ParticleData[Entity["Particle","Electron"],"Mass"]/1000],
QuantityMagnitude[ParticleData[Entity["Particle","Muon"],"Mass"]/1000],
QuantityMagnitude[ParticleData[Entity["Particle","PiMinus"],"Mass"]/1000],
QuantityMagnitude[ParticleData[Entity["Particle","KMinus"],"Mass"]/1000],
QuantityMagnitude[ParticleData[Entity["Particle","Proton"],"Mass"]/1000]
};
theParts={"Ele","Muo","Pio","Kao","Pro"};
toMass=AssociationThread[theParts,thePartMasses];
Print[thePartMasses=Map[SetPrecision[#,7]&,thePartMasses]];
deltaMassSquare=Differences[thePartMasses^2];
Print[nf[toMass]];
Print[Precision/@thePartMasses];
Print[nf[thePartMasses]];
Print[nf[thePartMasses^2]];
masses={m1,m2,m3,m4,m5}=thePartMasses;


(* ::Input::Initialization:: *)
Unprotect[mEle,mMuo,mPio,mKao,mPro,theHadronMasses]
ClearAll[mEle,mMuo,mPio,mKao,mPro,theHadronMasses]
theHadronMasses=thePartMasses[[3;;5]];
{mEle,mMuo,mPio,mKao,mPro}=thePartMasses
nf@N@Table[3^(k/3),{k,3,-3,-1}]
nf[0.001*0.06*Table[3^(k/3),{k,3,-3,-1}]]
Protect[mEle,mMuo,mPio,mKao,mPro,theHadronMasses]


(* ::Input::Initialization:: *)
tC[\[Beta]_,theE_]:=1000*thetaC[\[Beta],theRefrIndex[\[Lambda][theE]]];
tCAllPart[p_,theE_]:=Module[{},Table[1000*thetaC[betaPart[thePartMasses[[j]],p],theRefrIndex[\[Lambda][theE]]],{j,1,5}]];
tpl[mass_,mom_,\[Lambda]_]:=1000*thetaC[betaPart[mass,mom],theRefrIndex[\[Lambda]]];


(* ::Input::Initialization:: *)
(*OLD OK*)
(*chrnkvAngle[m_,p_,\[Lambda]_]:=Module[{z},z=1/(betaPart[m,p]*theRefrIndex[\[Lambda]]);
z=Map[Min[#,+1]&,z];
Return[Chop[ArcCos[z]]]
];*)


(*chrnkvAngle[m_,p_,\[Lambda]_]:=Module[{z},
z=1/(betaPart[m,p]*theRefrIndex[\[Lambda]]); (* It has to be positive *)
z=Min[z,1]; (* z is non negative *)
Return[Chop[ArcCos[z]]]
];*)

(*chrnkvAngle[m_,p_,\[Lambda]_]:=Module[{z},z=1/(betaPart[m,p]*theRefrIndex[\[Lambda]]);
z=Min[#,1]&/@Flatten[{z}];
Chop[ArcCos[z]]];*)


(* ::Subsubtitle:: *)
(*TO DO*)


(* ::Input::Initialization:: *)
(**************************************************************************************************)
(* General/generalized cherenkov angle formula *)
(**************************************************************************************************)
(*theRefrIndex[x_]:=1/(1+x/1000000000)*)
(*
k=n omega/c = 2Pi/lambda
lambda=2 Pi c/ n / omega 
 omega =2 Pi c/ n/lambda
theRefrIndex[\[Lambda]]=theRefrIndex[\[Lambda]]
D[n[\[Omega]],\[Omega]]=D[n[\[Omega]],\[Lambda]]*D[\[Lambda],\[Omega]]
*)
(*
g[m_,p_,\[Omega]_]:=
Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1]-(1/Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1])*\[Omega]*theRefrIndex[\[Lambda]0]*(betaPart[m,p])^2*D[n[\[Omega]],\[Omega]];
g[m,p,\[Omega]]
Print[Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1]-(1/Sqrt[(theRefrIndex[\[Lambda]0]*betaPart[m,p])^2-1])\[Omega]0*theRefrIndex[\[Lambda]0]];
chrnkvAngleGeneral[m_,p_,\[Epsilon]_]:=ArcCot[D[\[Epsilon]*Tan[ArcCos[1/(betaPart[m,p]*theRefrIndex[\[Lambda][\[Epsilon]]])]],\[Epsilon]]];
Print@Plot[chrnkvAngleGeneral[0.140,150,s]-Pi/2,{s,3,4}];
Print@Plot[chrnkvAngle[0.140,150,\[Lambda][s]],{s,3,4}];
*)


(* ::Subtitle:: *)
(*END*)


(* ::Input::Initialization:: *)
(* !@#$% ??? Do not bulk protect still undefined variables inside := *)
Protect[
bet,beta,betaCherenkovThreshold,betaInfinity,betaPart,betaParticleFromMassAndMomentum,betaPartThr,betThr,chrnkvAngle,deltaMassSquare,energy,epsilonQuantum,gam,gamma,gammaCherenkovThreshold,gammaPart,gammaParticleFromMassAndMomentum,gamThr,m1,m2,m3,m4,m5,mass,masses,momentum,momentumCherenkovThreshold,momentumFromMassAndBeta,momentumFromMassAndGamma,momentumPart,momentumThr,momThr,numPrecision,numRelPho,precisionify,tC,tCAllPart,theHighPrecision,thePartMasses,theParts,thetaC,thetaChr,thetaChrTheMax,thisNumRelChr,thisThetaChr,toMass,tpl
];


(* ::Input::Initialization:: *)
EndPackage[];


(* ::Input::Initialization:: *)
endEvalPrintOut[];


packageBanner["END physicsGeneral"];

